/* Generated by supernote_module_generator. Do not edit. */
export type SupernoteErrorCode =
  | 'RESOURCE_EXHAUSTED'
  | 'CANCELLED'
  | 'FEATURE_CLOSED'
  | 'IMPLEMENTATION_ERROR'
  | 'INTERNAL';

export class SupernoteError extends Error {
  readonly code: SupernoteErrorCode;
}

export type SupernoteValidationReason =
  | 'ARITY_MISMATCH'
  | 'TYPE_MISMATCH'
  | 'NOMINAL_MISMATCH'
  | 'MISSING_FIELD'
  | 'INVALID_ENUM'
  | 'OUT_OF_RANGE'
  | 'LIMIT_EXCEEDED';

export interface SupernoteValidationDetails {
  readonly reason: SupernoteValidationReason;
  readonly path: string;
  readonly expected: string;
  readonly actual: string;
}

export type SupernoteTypeError = TypeError & SupernoteValidationDetails;
export type SupernoteRangeError = RangeError & SupernoteValidationDetails;
export type SupernoteValidationResult =
  | {readonly ok: true}
  | {readonly ok: false; readonly error: SupernoteTypeError | SupernoteRangeError};

export interface SupernoteCallable<Arguments extends unknown[], Result> {
  (...args: Arguments): Result;
  accepts(...args: unknown[]): boolean;
  checkArguments(...args: unknown[]): SupernoteValidationResult;
}

export interface SupernoteTypeCompanion<Value> {
  is(value: unknown): value is Value;
  check(value: unknown): SupernoteValidationResult;
}

export type SupernoteFeatureStatus =
  | 'available'
  | 'runtime-unavailable'
  | 'feature-unavailable';

export interface SupernoteNativeObjectInfo {
  readonly type: string;
  readonly originFamily: 'cpp' | 'jvm';
}

export function isFeatureAvailable(): boolean;
export function getFeatureStatus(): SupernoteFeatureStatus;
export function nativeObjectInfo(value: unknown): SupernoteNativeObjectInfo | undefined;
export function isSupernoteTypeError(value: unknown): value is SupernoteTypeError;
export function isSupernoteRangeError(value: unknown): value is SupernoteRangeError;

export type Color = 'RED' | 'BLUE';

declare const __supernoteBrand_OtherStroke: unique symbol;
export interface OtherStroke {
  readonly [__supernoteBrand_OtherStroke]: void;
}

export interface Point {
  x: number;
  tags: (string | null)[];
  color: Color;
}

declare const __supernoteBrand_Receipt: unique symbol;
export interface Receipt {
  readonly [__supernoteBrand_Receipt]: void;
  status: SupernoteCallable<[], string>;
}

declare const __supernoteBrand_Stroke: unique symbol;
export interface Stroke {
  readonly [__supernoteBrand_Stroke]: void;
  readonly id: bigint;
  label: string;
  transform: SupernoteCallable<[offset: Point], Promise<Stroke>>;
}

declare const __supernoteBrand_Tools: unique symbol;
export interface Tools {
  readonly [__supernoteBrand_Tools]: void;
}

export interface DrawingFeature {
  Color: SupernoteTypeCompanion<Color>;
  OtherStroke: SupernoteTypeCompanion<OtherStroke>;
  Point: SupernoteTypeCompanion<Point>;
  Receipt: SupernoteTypeCompanion<Receipt>;
  Stroke: SupernoteTypeCompanion<Stroke> & {
    create: SupernoteCallable<[point: Point], Stroke>;
    fromPoints: SupernoteCallable<[points: Point[]], Stroke>;
  };
  Tools: SupernoteTypeCompanion<Tools> & {
    version: SupernoteCallable<[], string>;
  };
  load: SupernoteCallable<[], Receipt>;
  maybe: SupernoteCallable<[strokes: (Stroke | null)[]], Stroke[] | null>;
  useOther: SupernoteCallable<[other: OtherStroke], void>;
}

declare const feature: DrawingFeature;
export default feature;
