"""Render the shared generated C++ and JVM conversion-budget kernel."""
from __future__ import annotations

from .conversion import ConversionLimits, DEFAULT_CONVERSION_LIMITS


def render_cpp_conversion_kernel(
    limits: ConversionLimits = DEFAULT_CONVERSION_LIMITS,
) -> str:
    return f'''// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

namespace supernote::conversion {{

enum class FailureKind {{ TYPE, RANGE, ALLOCATION }};

class Failure final : public std::runtime_error {{
 public:
  Failure(FailureKind kind, std::string path, std::string message)
      : std::runtime_error(path + ": " + message),
        kind_(kind),
        path_(std::move(path)) {{}}

  [[nodiscard]] FailureKind kind() const noexcept {{ return kind_; }}
  [[nodiscard]] const std::string &path() const noexcept {{ return path_; }}

 private:
  FailureKind kind_;
  std::string path_;
}};

struct Limits final {{
  static constexpr std::uint64_t max_depth = {limits.max_depth}ULL;
  static constexpr std::uint64_t max_array_length = {limits.max_array_length}ULL;
  static constexpr std::uint64_t max_visited_nodes = {limits.max_visited_nodes}ULL;
  static constexpr std::uint64_t max_string_bytes = {limits.max_string_bytes}ULL;
  static constexpr std::uint64_t max_byte_buffer_bytes = {limits.max_byte_buffer_bytes}ULL;
  static constexpr std::uint64_t max_temporary_bytes = {limits.max_temporary_bytes}ULL;
}};

class AllocationGate final {{
 public:
  explicit AllocationGate(
      std::optional<std::uint64_t> fail_after = std::nullopt) noexcept
      : fail_after_(fail_after) {{}}

  void reserve(std::string_view path) {{
    if (fail_after_ && reservations_ >= *fail_after_) {{
      throw Failure(
          FailureKind::ALLOCATION, std::string(path),
          "injected temporary allocation failure");
    }}
    reservations_ = checked_add(reservations_, 1, path, "reservation");
  }}

  [[nodiscard]] std::uint64_t reservations() const noexcept {{
    return reservations_;
  }}

 private:
  static std::uint64_t checked_add(
      std::uint64_t left, std::uint64_t right,
      std::string_view path, std::string_view label) {{
    constexpr auto max_counter =
        static_cast<std::uint64_t>(std::numeric_limits<std::int64_t>::max());
    if (left > max_counter || right > max_counter - left) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          std::string(label) + " counter overflow");
    }}
    return left + right;
  }}

  std::optional<std::uint64_t> fail_after_;
  std::uint64_t reservations_ = 0;
}};

class Budget final {{
 public:
  explicit Budget(AllocationGate *allocation_gate = nullptr) noexcept
      : allocation_gate_(allocation_gate) {{}}

  void visit(std::string_view path, std::uint64_t depth) {{
    if (depth > Limits::max_depth) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          "conversion depth exceeds configured limit");
    }}
    visited_nodes_ = checked_add(
        visited_nodes_, 1, path, "visited-node");
    if (visited_nodes_ > Limits::max_visited_nodes) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          "conversion visits exceed configured limit");
    }}
  }}

  void check_array_length(std::string_view path, std::uint64_t length) const {{
    if (length > Limits::max_array_length) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          "array length exceeds configured limit");
    }}
  }}

  void check_string_bytes(std::string_view path, std::uint64_t size) const {{
    if (size > Limits::max_string_bytes) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          "UTF-8 string exceeds configured limit");
    }}
  }}

  void check_byte_buffer(std::string_view path, std::uint64_t size) const {{
    if (size > Limits::max_byte_buffer_bytes) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          "byte buffer exceeds configured limit");
    }}
  }}

  void reserve(std::string_view path, std::uint64_t amount) {{
    if (allocation_gate_ != nullptr) allocation_gate_->reserve(path);
    temporary_bytes_ = checked_add(
        temporary_bytes_, amount, path, "temporary-byte");
    if (temporary_bytes_ > Limits::max_temporary_bytes) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          "temporary allocation exceeds configured limit");
    }}
  }}

  [[nodiscard]] std::uint64_t visited_nodes() const noexcept {{
    return visited_nodes_;
  }}
  [[nodiscard]] std::uint64_t temporary_bytes() const noexcept {{
    return temporary_bytes_;
  }}

 private:
  static std::uint64_t checked_add(
      std::uint64_t left, std::uint64_t right,
      std::string_view path, std::string_view label) {{
    constexpr auto max_counter =
        static_cast<std::uint64_t>(std::numeric_limits<std::int64_t>::max());
    if (left > max_counter || right > max_counter - left) {{
      throw Failure(
          FailureKind::RANGE, std::string(path),
          std::string(label) + " counter overflow");
    }}
    return left + right;
  }}

  AllocationGate *allocation_gate_;
  std::uint64_t visited_nodes_ = 0;
  std::uint64_t temporary_bytes_ = 0;
}};

inline std::string field_path(std::string_view parent, std::string_view field) {{
  std::string result(parent);
  result.push_back('.');
  result.append(field);
  return result;
}}

inline std::string index_path(std::string_view parent, std::uint64_t index) {{
  return std::string(parent) + "[" + std::to_string(index) + "]";
}}

}}  // namespace supernote::conversion
'''


def render_jvm_conversion_kernel(
    limits: ConversionLimits = DEFAULT_CONVERSION_LIMITS,
) -> str:
    return f'''// Generated by supernote_module_generator. Do not edit.
package supernote.generated.runtime

internal object SupernoteConversionLimits {{
  const val MAX_DEPTH: Long = {limits.max_depth}L
  const val MAX_ARRAY_LENGTH: Long = {limits.max_array_length}L
  const val MAX_VISITED_NODES: Long = {limits.max_visited_nodes}L
  const val MAX_STRING_BYTES: Long = {limits.max_string_bytes}L
  const val MAX_BYTE_BUFFER_BYTES: Long = {limits.max_byte_buffer_bytes}L
  const val MAX_TEMPORARY_BYTES: Long = {limits.max_temporary_bytes}L
}}

internal enum class SupernoteConversionFailureKind {{ TYPE, RANGE, ALLOCATION }}

internal class SupernoteConversionFailure(
  val kind: SupernoteConversionFailureKind,
  val path: String,
  message: String,
) : IllegalArgumentException("$path: $message")

internal class SupernoteAllocationGate(private val failAfter: Long? = null) {{
  var reservations: Long = 0
    private set

  fun reserve(path: String) {{
    if (failAfter != null && reservations >= failAfter) {{
      throw SupernoteConversionFailure(
        SupernoteConversionFailureKind.ALLOCATION,
        path,
        "injected temporary allocation failure",
      )
    }}
    reservations = checkedAdd(reservations, 1, path, "reservation")
  }}
}}

internal class SupernoteConversionBudget(
  private val allocationGate: SupernoteAllocationGate? = null,
) {{
  var visitedNodes: Long = 0
    private set
  var temporaryBytes: Long = 0
    private set

  fun visit(path: String, depth: Long) {{
    if (depth > SupernoteConversionLimits.MAX_DEPTH) range(path, "conversion depth")
    visitedNodes = checkedAdd(visitedNodes, 1, path, "visited-node")
    if (visitedNodes > SupernoteConversionLimits.MAX_VISITED_NODES) {{
      range(path, "conversion visits")
    }}
  }}

  fun checkArrayLength(path: String, length: Long) {{
    if (length > SupernoteConversionLimits.MAX_ARRAY_LENGTH) range(path, "array length")
  }}

  fun checkStringBytes(path: String, size: Long) {{
    if (size > SupernoteConversionLimits.MAX_STRING_BYTES) range(path, "UTF-8 string")
  }}

  fun checkByteBuffer(path: String, size: Long) {{
    if (size > SupernoteConversionLimits.MAX_BYTE_BUFFER_BYTES) range(path, "byte buffer")
  }}

  fun reserve(path: String, amount: Long) {{
    if (amount < 0) range(path, "negative allocation size")
    allocationGate?.reserve(path)
    temporaryBytes = checkedAdd(temporaryBytes, amount, path, "temporary-byte")
    if (temporaryBytes > SupernoteConversionLimits.MAX_TEMPORARY_BYTES) {{
      range(path, "temporary allocation")
    }}
  }}

  private fun range(path: String, label: String): Nothing =
    throw SupernoteConversionFailure(
      SupernoteConversionFailureKind.RANGE,
      path,
      "$label exceeds configured limit",
    )
}}

private fun checkedAdd(left: Long, right: Long, path: String, label: String): Long {{
  if (left < 0 || right < 0 || right > Long.MAX_VALUE - left) {{
    throw SupernoteConversionFailure(
      SupernoteConversionFailureKind.RANGE,
      path,
      "$label counter overflow",
    )
  }}
  return left + right
}}

internal fun conversionFieldPath(parent: String, field: String): String = "$parent.$field"
internal fun conversionIndexPath(parent: String, index: Long): String = "$parent[$index]"
'''
