"""Generate typed handwritten-C++ facades for hidden V2 bindings."""
from __future__ import annotations

import json
import re
from pathlib import Path

from .binding_codegen import (
    scan_cpp_class_source_model,
    scan_cpp_source_model,
)
from .jvm_manifest import JvmSourceManifest
from .semantic import (
    DeclarationRole,
    ExecutionMode,
    SemanticApi,
    SemanticBinding,
    SemanticClass,
    SemanticClassKind,
    SemanticType,
)
from .source_models import CppClassSource, CppFunctionSource, CppMethodSource


def internal_header_path(feature_id: str) -> str:
    return f"include/supernote/{_suffix(feature_id)}/internal.hpp"


def render_cpp_internal_facade(
    module_root: Path,
    *,
    module_name: str,
    feature_id: str,
    jvm_manifest: JvmSourceManifest | None = None,
    jvm_semantic: SemanticApi | None = None,
) -> tuple[str, str]:
    native_root = module_root / "android/src/main/cpp"
    functions = (
        [
            item
            for item in scan_cpp_source_model(
                module_root, module_name=module_name
            )
            if item.intent.role is DeclarationRole.INTERNAL
        ]
        if native_root.is_dir()
        else []
    )
    services = (
        [
            item
            for item in scan_cpp_class_source_model(
                module_root, module_name=module_name
            )
            if item.intent.role is DeclarationRole.INTERNAL
        ]
        if native_root.is_dir()
        else []
    )
    if (jvm_manifest is None) != (jvm_semantic is None):
        raise ValueError("JVM source and semantic models must be supplied together")
    jvm_functions = []
    jvm_services = []
    if jvm_manifest is not None and jvm_semantic is not None:
        jvm_sources = {
            declaration.provenance.declaration_id: declaration
            for owner in jvm_manifest.owners
            for declaration in owner.declarations
        }
        jvm_functions = [
            (binding, jvm_sources[binding.source.declaration_id])
            for binding in jvm_semantic.functions
            if binding.capabilities.role is DeclarationRole.INTERNAL
        ]
        jvm_services = [
            item
            for item in jvm_semantic.classes
            if item.kind is SemanticClassKind.INTERNAL_SERVICE
        ]
    namespace = internal_namespace(module_name)
    declarations = [_function_declaration(item) for item in functions]
    declarations.extend(_service_declaration(item) for item in services)
    declarations.extend(
        _jvm_function_declaration(binding) for binding, _ in jvm_functions
    )
    declarations.extend(_jvm_service_declaration(item) for item in jvm_services)
    header = f'''// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include <supernote/runtime.hpp>

namespace supernote::internal::{namespace} {{

{chr(10).join(declarations)}

}}  // namespace supernote::internal::{namespace}
'''
    forward = [_function_forward(item) for item in functions]
    includes = "\n".join(
        f'#include "{item.include}"' for item in services
    )
    definitions = [
        _function_definition(item, namespace) for item in functions
    ]
    definitions.extend(
        _service_definition(item, namespace) for item in services
    )
    source = f'''// Generated by supernote_module_generator. Do not edit.
#include <supernote/{_suffix(feature_id)}/internal.hpp>

#include "runtime_services.hpp"
{includes}

#include <android/log.h>

#include <exception>
#include <memory>
#include <stdexcept>
#include <utility>

{chr(10).join(forward)}

namespace supernote::internal::{namespace} {{
namespace {{

constexpr char kInternalLogTag[] = "SupernoteV2Internal";

std::shared_ptr<supernote::runtime::FeatureSession> require_feature() {{
  auto feature = supernote::runtime::current_feature_session();
  if (!feature ||
      feature->state() != supernote::runtime::FeatureState::ACTIVE) {{
    throw supernote::Error(
        supernote::ErrorCode::FEATURE_CLOSED, "feature is closed");
  }}
  return feature;
}}

template <typename Callback, typename Result>
void deliver_callback(Callback &callback, Result result) noexcept {{
  try {{
    callback(std::move(result));
  }} catch (const std::exception &error) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kInternalLogTag,
        "internal completion callback threw: %s", error.what());
  }} catch (...) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kInternalLogTag,
        "internal completion callback threw an unknown exception");
  }}
}}

}}  // namespace

{chr(10).join(definitions)}

}}  // namespace supernote::internal::{namespace}
'''
    return header, source


def _function_declaration(item: CppFunctionSource) -> str:
    parameters = _parameters(item.parameters)
    if item.intent.execution is ExecutionMode.ASYNC:
        callback = _callback(item.return_type_spelling)
        parameters = _append_parameter(parameters, f"{callback} completion")
        return f"void {item.cpp_name}({parameters});"
    return f"{item.return_type_spelling} {item.cpp_name}({parameters});"


def _function_forward(item: CppFunctionSource) -> str:
    return (
        f"{item.return_type_spelling} {item.cpp_name}("
        f"{_parameters(item.parameters)});"
    )


def _function_definition(item: CppFunctionSource, namespace: str) -> str:
    parameters = _parameters(item.parameters)
    arguments = ", ".join(parameter.name for parameter in item.parameters)
    call = f"::{item.cpp_name}({arguments})"
    if item.intent.execution is ExecutionMode.ASYNC:
        callback = _callback(item.return_type_spelling)
        signature = _append_parameter(parameters, f"{callback} completion")
        return _async_definition(
            f"void {item.cpp_name}({signature})",
            call,
            item.return_type_spelling,
            item.parameters,
        )
    return _sync_definition(
        f"{item.return_type_spelling} {item.cpp_name}({parameters})",
        call,
        item.return_type_spelling,
    )


def _service_declaration(item: CppClassSource) -> str:
    methods = [
        method
        for method in item.methods
        if method.intent.role is DeclarationRole.INTERNAL
    ]
    rows = []
    for method in methods:
        parameters = _parameters(method.parameters)
        if method.intent.execution is ExecutionMode.ASYNC:
            parameters = _append_parameter(
                parameters,
                f"{_callback(method.return_type_spelling)} completion",
            )
            rows.append(f"  static void {method.cpp_name}({parameters});")
        else:
            rows.append(
                f"  static {method.return_type_spelling} "
                f"{method.cpp_name}({parameters});"
            )
    return (
        f"struct {item.cpp_name} final {{\n"
        + "\n".join(rows)
        + "\n};"
    )


def _service_definition(item: CppClassSource, namespace: str) -> str:
    rows = []
    for method in item.methods:
        if method.intent.role is not DeclarationRole.INTERNAL:
            continue
        parameters = _parameters(method.parameters)
        arguments = ", ".join(parameter.name for parameter in method.parameters)
        service = (
            "feature->service<::"
            f"{item.cpp_name}>({json.dumps(item.provenance.declaration_id)}, [] {{\n"
            f"      return std::make_shared<::{item.cpp_name}>();\n"
            "    })"
        )
        call = f"service->{method.cpp_name}({arguments})"
        if method.intent.execution is ExecutionMode.ASYNC:
            signature = _append_parameter(
                parameters,
                f"{_callback(method.return_type_spelling)} completion",
            )
            rows.append(
                _async_definition(
                    f"void {item.cpp_name}::{method.cpp_name}({signature})",
                    call,
                    method.return_type_spelling,
                    method.parameters,
                    service_setup=f"    auto service = {service};\n",
                )
            )
        else:
            rows.append(
                _sync_definition(
                    f"{method.return_type_spelling} "
                    f"{item.cpp_name}::{method.cpp_name}({parameters})",
                    call,
                    method.return_type_spelling,
                    service_setup=f"    auto service = {service};\n",
                )
            )
    return "\n\n".join(rows)


def _sync_definition(
    signature: str,
    call: str,
    result: str,
    *,
    service_setup: str = "",
) -> str:
    invoke = f"{call};\n    return;" if result == "void" else f"return {call};"
    return f'''{signature} {{
  auto feature = require_feature();
  try {{
{service_setup}    {invoke}
  }} catch (const supernote::Error &) {{
    throw;
  }} catch (const std::exception &error) {{
    throw supernote::Error(
        supernote::ErrorCode::IMPLEMENTATION_ERROR, error.what());
  }} catch (...) {{
    throw supernote::Error(
        supernote::ErrorCode::IMPLEMENTATION_ERROR,
        "unknown C++ implementation failure");
  }}
}}'''


def _async_definition(
    signature: str,
    call: str,
    result: str,
    parameters,
    *,
    service_setup: str = "",
) -> str:
    captures = ", ".join(
        f"{item.name} = std::move({item.name})" for item in parameters
    )
    capture_suffix = f", {captures}" if captures else ""
    if result == "void":
        invoke = (
            f"{call};\n"
            "      outcome = supernote::Result<void>::success();"
        )
        result_type = "supernote::Result<void>"
    else:
        invoke = (
            f"outcome = supernote::Result<{result}>::success({call});"
        )
        result_type = f"supernote::Result<{result}>"
    return f'''{signature} {{
  auto feature = require_feature();
  if (!completion) {{
    throw supernote::Error(
        supernote::ErrorCode::INTERNAL, "completion callback is empty");
  }}
  auto callback = std::make_shared<decltype(completion)>(
      std::move(completion));
  auto operation = feature->accept({{}}, std::move(callback));
  if (!operation) {{
    throw supernote::Error(
        supernote::ErrorCode::FEATURE_CLOSED, "feature is closed");
  }}
  std::weak_ptr<supernote::runtime::FeatureSession> weak_feature = feature;
  auto work = supernote::runtime::process_services().workers().submit(
      [operation, weak_feature{capture_suffix}](
          supernote::runtime::CancellationToken executor_cancel) mutable {{
        if (executor_cancel.is_cancelled() ||
            operation->cancellation_token().is_cancelled()) return;
        auto feature = weak_feature.lock();
        if (!feature) return;
        supernote::runtime::FeatureCallScope scope(feature);
        {result_type} outcome = {result_type}::failure(supernote::Error(
            supernote::ErrorCode::INTERNAL, "operation did not complete"));
        try {{
{service_setup}      feature.reset();
      {invoke}
        }} catch (const supernote::Error &error) {{
          outcome = {result_type}::failure(error);
        }} catch (const std::exception &error) {{
          outcome = {result_type}::failure(supernote::Error(
              supernote::ErrorCode::IMPLEMENTATION_ERROR, error.what()));
        }} catch (...) {{
          outcome = {result_type}::failure(supernote::Error(
              supernote::ErrorCode::IMPLEMENTATION_ERROR,
              "unknown C++ implementation failure"));
        }}
        feature.reset();
        auto completion_feature = weak_feature.lock();
        if (operation->cancellation_token().is_cancelled() ||
            !completion_feature ||
            !completion_feature->claim_internal_completion(operation)) return;
        auto callback = std::static_pointer_cast<decltype(completion)>(
            operation->take_internal_completion());
        if (!callback) return;
        deliver_callback(*callback, std::move(outcome));
      }});
  operation->set_work(work);
  if (!work.accepted()) {{
    auto cleanup = supernote::runtime::process_services().cleanup();
    auto exhausted = [operation, weak_feature]() mutable {{
      auto completion_feature = weak_feature.lock();
      if (!completion_feature ||
          !completion_feature->claim_internal_completion(operation)) return;
      auto callback = std::static_pointer_cast<decltype(completion)>(
          operation->take_internal_completion());
      if (!callback) return;
      auto result = {result_type}::failure(supernote::Error(
          supernote::ErrorCode::RESOURCE_EXHAUSTED,
          "Supernote worker queue is full"));
      deliver_callback(*callback, std::move(result));
    }};
    if (!cleanup || !cleanup->submit(std::move(exhausted))) {{
      if (feature->claim_internal_completion(operation)) {{
        operation->take_internal_completion();
      }}
      throw supernote::Error(
          supernote::ErrorCode::INTERNAL,
          "cannot schedule internal completion callback");
    }}
  }}
}}'''


def _parameters(parameters) -> str:
    return ", ".join(
        f"{item.type_spelling} {item.name}" for item in parameters
    )


def _append_parameter(parameters: str, value: str) -> str:
    return f"{parameters}, {value}" if parameters else value


def _callback(result: str) -> str:
    semantic_result = (
        "supernote::Result<void>"
        if result == "void"
        else f"supernote::Result<{result}>"
    )
    return f"std::function<void({semantic_result})>"


def internal_namespace(module_name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]", "_", module_name)
    return value if value and not value[0].isdigit() else f"Feature_{value}"


def _jvm_function_declaration(item: SemanticBinding) -> str:
    parameters = _semantic_parameters(item)
    if item.execution is ExecutionMode.ASYNC:
        parameters = _append_parameter(
            parameters, f"{_semantic_callback(item.result)} completion"
        )
        return f"void {item.name}({parameters});"
    return f"{_semantic_cpp_type(item.result)} {item.name}({parameters});"


def _jvm_service_declaration(item: SemanticClass) -> str:
    rows = []
    for method in item.methods:
        parameters = _semantic_parameters(method)
        if method.execution is ExecutionMode.ASYNC:
            parameters = _append_parameter(
                parameters, f"{_semantic_callback(method.result)} completion"
            )
            rows.append(f"  static void {method.name}({parameters});")
        else:
            rows.append(
                f"  static {_semantic_cpp_type(method.result)} "
                f"{method.name}({parameters});"
            )
    return f"struct {item.name} final {{\n" + "\n".join(rows) + "\n};"


def _semantic_parameters(item: SemanticBinding) -> str:
    return ", ".join(
        f"{_semantic_cpp_type(parameter.type)} {parameter.name}"
        for parameter in item.parameters
    )


def _semantic_callback(result: SemanticType) -> str:
    return (
        "std::function<void(supernote::Result<"
        f"{_semantic_cpp_type(result)}>)>"
        if result is not SemanticType.VOID
        else "std::function<void(supernote::Result<void>)>"
    )


def _semantic_cpp_type(value: SemanticType) -> str:
    return {
        SemanticType.VOID: "void",
        SemanticType.BOOL: "bool",
        SemanticType.INT32: "std::int32_t",
        SemanticType.INT64: "std::int64_t",
        SemanticType.FLOAT32: "float",
        SemanticType.FLOAT64: "double",
        SemanticType.STRING: "std::string",
        SemanticType.BYTES: "std::vector<std::byte>",
    }[value]


def _suffix(feature_id: str) -> str:
    prefix = "supernote:feature:"
    suffix = feature_id.removeprefix(prefix)
    if not feature_id.startswith(prefix) or not re.fullmatch(r"[0-9a-f]{16}", suffix):
        raise ValueError(f"invalid feature identity {feature_id!r}")
    return suffix
