"""Generate package-local CMake and JVM integration artifacts."""
from __future__ import annotations

import json


NATIVE_RUNTIME_ABI = "supernote-jsi-v1"


def feature_cmake_target(feature_id: str) -> str:
    """Return the stable collision-resistant CMake target for one feature."""

    prefix = "supernote:feature:"
    if not feature_id.startswith(prefix):
        raise ValueError(f"invalid Supernote feature identity: {feature_id!r}")
    suffix = feature_id.removeprefix(prefix)
    if len(suffix) != 16 or any(character not in "0123456789abcdef" for character in suffix):
        raise ValueError(f"invalid Supernote feature identity: {feature_id!r}")
    return f"supernote_feature_{suffix}"


def package_registration_symbol(feature_id: str) -> str:
    """Return the stable C symbol exported by package-local registration."""

    return f"supernote_package_registration_{feature_cmake_target(feature_id).removeprefix('supernote_feature_')}"


def package_native_installer_symbol(feature_id: str) -> str:
    """Return the C-linkage native installer symbol for one packed feature."""

    suffix = feature_cmake_target(feature_id).removeprefix("supernote_feature_")
    return f"supernote_package_install_native_{suffix}"


def package_jvm_installer_symbol(feature_id: str) -> str:
    """Return the C-linkage JVM installer symbol for one packed feature."""

    suffix = feature_cmake_target(feature_id).removeprefix("supernote_feature_")
    return f"supernote_package_install_jvm_{suffix}"


def render_package_registration(
    *,
    feature_id: str,
    package_name: str,
    public_name: str,
    has_jvm_installer: bool = False,
) -> tuple[str, str]:
    """Render identity plus callable installers retained from the static archive."""

    target = feature_cmake_target(feature_id)
    symbol = package_registration_symbol(feature_id)
    suffix = target.removeprefix("supernote_feature_")
    native_installer = package_native_installer_symbol(feature_id)
    jvm_installer = package_jvm_installer_symbol(feature_id)
    header = f'''// Generated by supernote_module_generator. Do not edit.
#pragma once

struct SupernotePackageRegistration {{
  const char *feature_id;
  const char *package_name;
  const char *public_name;
  const char *cmake_target;
}};

extern "C" const SupernotePackageRegistration *{symbol}() noexcept;
extern "C" void {native_installer}(
    void *runtime, void *feature_registry, const void *feature_session);
'''
    if has_jvm_installer:
        header += f'''extern "C" void {jvm_installer}(
    void *runtime, void *feature_registry, const void *feature_session);
'''
    source = f'''// Generated by supernote_module_generator. Do not edit.
#include "package_registration.hpp"

#include <memory>

namespace facebook::jsi {{
class Object;
class Runtime;
}}
namespace supernote::runtime {{
class FeatureSession;
}}

namespace supernote::generated::feature_{suffix} {{
void register_feature(
    facebook::jsi::Runtime &runtime,
    facebook::jsi::Object &feature_registry,
    const std::shared_ptr<supernote::runtime::FeatureSession> &feature_session);
}}
'''
    if has_jvm_installer:
        source += f'''namespace supernote::generated::jvm_feature_{suffix} {{
void register_jvm_feature(
    facebook::jsi::Runtime &runtime,
    facebook::jsi::Object &feature_registry,
    const std::shared_ptr<supernote::runtime::FeatureSession> &feature_session);
}}
'''
    source += f'''
namespace {{
constexpr SupernotePackageRegistration kRegistration{{
    {json.dumps(feature_id)},
    {json.dumps(package_name)},
    {json.dumps(public_name)},
    {json.dumps(target)},
}};
}}  // namespace

extern "C" const SupernotePackageRegistration *{symbol}() noexcept {{
  return &kRegistration;
}}

extern "C" void {native_installer}(
    void *runtime, void *feature_registry, const void *feature_session) {{
  supernote::generated::feature_{suffix}::register_feature(
      *static_cast<facebook::jsi::Runtime *>(runtime),
      *static_cast<facebook::jsi::Object *>(feature_registry),
      *static_cast<const std::shared_ptr<supernote::runtime::FeatureSession> *>(
          feature_session));
}}
'''
    if has_jvm_installer:
        source += f'''
extern "C" void {jvm_installer}(
    void *runtime, void *feature_registry, const void *feature_session) {{
  supernote::generated::jvm_feature_{suffix}::register_jvm_feature(
      *static_cast<facebook::jsi::Runtime *>(runtime),
      *static_cast<facebook::jsi::Object *>(feature_registry),
      *static_cast<const std::shared_ptr<supernote::runtime::FeatureSession> *>(
          feature_session));
}}
'''
    return header, source


def render_jvm_package_registration(
    *, feature_id: str, package_name: str, public_name: str
) -> tuple[str, str]:
    """Return the path and source of the package's generator-produced JVM record."""

    suffix = feature_cmake_target(feature_id).removeprefix("supernote_feature_")
    relative = ".supernote-generated/android/jvm/JvmRegistration.java"
    source = f'''// Generated by supernote_module_generator. Do not edit.
package supernote.generated.packages.feature_{suffix};

public final class JvmRegistration {{
  private JvmRegistration() {{}}

  public static String featureId() {{ return {json.dumps(feature_id)}; }}
  public static String packageName() {{ return {json.dumps(package_name)}; }}
  public static String publicName() {{ return {json.dumps(public_name)}; }}
  public static String cmakeTarget() {{ return {json.dumps(feature_cmake_target(feature_id))}; }}
}}
'''
    return relative, source


def render_package_cmake(
    *,
    feature_id: str,
    binding_sources: tuple[str, ...],
) -> str:
    """Render the package-owned feature target and authored-CMake hook."""

    target = feature_cmake_target(feature_id)
    sources = "\n".join(
        f'    "${{CMAKE_CURRENT_LIST_DIR}}/{path}"' for path in binding_sources
    )
    return f'''# Generated by supernote_module_generator. Do not edit.
cmake_minimum_required(VERSION 3.24)
cmake_policy(SET CMP0131 NEW)

set(_SUPERNOTE_PACKAGE_ROOT "${{CMAKE_CURRENT_LIST_DIR}}/../..")
set(_SUPERNOTE_FEATURE_TARGET {target})

if(TARGET "${{_SUPERNOTE_FEATURE_TARGET}}")
  message(FATAL_ERROR
    "Supernote feature target collision: ${{_SUPERNOTE_FEATURE_TARGET}}")
endif()
if(NOT DEFINED SUPERNOTE_RUNTIME_COMPILE_TARGET OR
   NOT TARGET "${{SUPERNOTE_RUNTIME_COMPILE_TARGET}}")
  message(FATAL_ERROR
    "SUPERNOTE_RUNTIME_COMPILE_TARGET must name the active runtime compile contract")
endif()
if(NOT DEFINED SUPERNOTE_RUNTIME_NATIVE_ABI OR
   NOT SUPERNOTE_RUNTIME_NATIVE_ABI STREQUAL "{NATIVE_RUNTIME_ABI}")
  message(FATAL_ERROR
    "Supernote native ABI mismatch: expected {NATIVE_RUNTIME_ABI}")
endif()

add_library(${{_SUPERNOTE_FEATURE_TARGET}} STATIC
{sources}
)
target_compile_features(
  ${{_SUPERNOTE_FEATURE_TARGET}} PUBLIC c_std_23 cxx_std_23)
set_target_properties(${{_SUPERNOTE_FEATURE_TARGET}} PROPERTIES
  POSITION_INDEPENDENT_CODE ON)
target_include_directories(${{_SUPERNOTE_FEATURE_TARGET}} PRIVATE
  "${{_SUPERNOTE_PACKAGE_ROOT}}"
  "${{CMAKE_CURRENT_LIST_DIR}}"
  "${{CMAKE_CURRENT_LIST_DIR}}/include")
target_link_libraries(
  ${{_SUPERNOTE_FEATURE_TARGET}} PRIVATE "${{SUPERNOTE_RUNTIME_COMPILE_TARGET}}")

if(EXISTS "${{_SUPERNOTE_PACKAGE_ROOT}}/CMakeLists.txt")
  set(SUPERNOTE_MODULE_TARGET "${{_SUPERNOTE_FEATURE_TARGET}}")
  add_subdirectory(
    "${{_SUPERNOTE_PACKAGE_ROOT}}"
    "${{CMAKE_CURRENT_BINARY_DIR}}/author"
    EXCLUDE_FROM_ALL)
  unset(SUPERNOTE_MODULE_TARGET)
endif()

get_target_property(_SUPERNOTE_FEATURE_KIND
                    ${{_SUPERNOTE_FEATURE_TARGET}} TYPE)
if(NOT _SUPERNOTE_FEATURE_KIND STREQUAL "STATIC_LIBRARY")
  message(FATAL_ERROR
    "Supernote feature target must remain a STATIC library")
endif()
set_target_properties(${{_SUPERNOTE_FEATURE_TARGET}} PROPERTIES
  POSITION_INDEPENDENT_CODE ON)

set(SUPERNOTE_PACKAGE_FEATURE_TARGET "${{_SUPERNOTE_FEATURE_TARGET}}" PARENT_SCOPE)
unset(_SUPERNOTE_FEATURE_KIND)
unset(_SUPERNOTE_FEATURE_TARGET)
unset(_SUPERNOTE_PACKAGE_ROOT)
'''
