"""Generate the one plugin-level V2 runtime/build component."""
from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import tempfile
import uuid

from .feature_model import PluginRuntimeRegistry


RUNTIME_RELATIVE_ROOT = Path("android/.supernote-module/v2-runtime")


def generated_runtime_files(registry: PluginRuntimeRegistry) -> dict[str, str]:
    """Return deterministic generated files for one compiled plugin component."""

    feature_rows = "\n".join(
        "    {"
        + json.dumps(entry.feature.feature_id)
        + ", "
        + json.dumps(entry.feature.public_name)
        + "},"
        for entry in registry.features
    )
    if not feature_rows:
        feature_rows = "    // No generated features are currently registered."
    component = registry.component_name
    cmake = f"""# Generated by supernote_module_generator. Do not edit.
cmake_minimum_required(VERSION 3.22.1)
project({component} LANGUAGES C CXX)

add_library({component} SHARED
    src/feature_registry.cpp
    src/runtime_services.cpp
)

target_compile_features({component} PRIVATE cxx_std_23)
"""
    header = """// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>

namespace supernote::generated {

struct FeatureDescriptor {
  const char *feature_id;
  const char *public_name;
};

const FeatureDescriptor *feature_registry_data() noexcept;
std::size_t feature_registry_size() noexcept;

}  // namespace supernote::generated
"""
    registry_source = f"""// Generated by supernote_module_generator. Do not edit.
#include "feature_registry.hpp"

#include <array>

namespace supernote::generated {{
namespace {{

constexpr std::array<FeatureDescriptor, {len(registry.features)}> kFeatures{{{{
{feature_rows}
}}}};

}}  // namespace

const FeatureDescriptor *feature_registry_data() noexcept {{
  return kFeatures.data();
}}

std::size_t feature_registry_size() noexcept {{
  return kFeatures.size();
}}

}}  // namespace supernote::generated
"""
    services = """// Generated by supernote_module_generator. Do not edit.
#include <cstdint>

namespace supernote::runtime {

// This object is intentionally defined in exactly one plugin-level compiled
// component. Feature bindings refer to this service set instead of compiling
// per-feature runtime singletons.
struct RuntimeServices {
  std::uint64_t component_generation = 0;
};

RuntimeServices &runtime_services() noexcept {
  static RuntimeServices services;
  return services;
}

}  // namespace supernote::runtime
"""
    ownership = {
        "schema_version": 1,
        "kind": "supernote_plugin_runtime_ownership",
        "component_name": component,
        "generator_version": registry.generator_version,
        "generated_files": [
            "CMakeLists.txt",
            "feature-registry.json",
            "ownership.json",
            "src/feature_registry.cpp",
            "src/feature_registry.hpp",
            "src/runtime_services.cpp",
        ],
    }
    return {
        "CMakeLists.txt": cmake,
        "feature-registry.json": (
            json.dumps(registry.manifest(), indent=2, sort_keys=True) + "\n"
        ),
        "ownership.json": json.dumps(ownership, indent=2, sort_keys=True) + "\n",
        "src/feature_registry.cpp": registry_source,
        "src/feature_registry.hpp": header,
        "src/runtime_services.cpp": services,
    }


def stage_plugin_runtime(plugin_root: Path, registry: PluginRuntimeRegistry) -> Path:
    """Stage a complete replacement without mutating the active component."""

    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    parent = destination.parent
    parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.tmp-", dir=parent)
    )
    try:
        for relative, content in generated_runtime_files(registry).items():
            target = temporary / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
        return temporary
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def activate_plugin_runtime(staged: Path, plugin_root: Path) -> Path | None:
    """Atomically activate staged generated files and return a rollback backup."""

    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    backup = None
    if destination.exists():
        backup = destination.parent / (
            f".{destination.name}.backup-{uuid.uuid4().hex}"
        )
        os.replace(destination, backup)
    try:
        os.replace(staged, destination)
        return backup
    except Exception:
        if backup is not None and backup.exists():
            os.replace(backup, destination)
        raise


def finalize_plugin_runtime(backup: Path | None) -> None:
    if backup is not None:
        shutil.rmtree(backup, ignore_errors=True)


def restore_plugin_runtime(plugin_root: Path, backup: Path | None) -> None:
    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    if backup is None:
        shutil.rmtree(destination, ignore_errors=True)
        return
    failed = destination.parent / f".{destination.name}.failed-{uuid.uuid4().hex}"
    if destination.exists():
        os.replace(destination, failed)
    os.replace(backup, destination)
    shutil.rmtree(failed, ignore_errors=True)


def generate_plugin_runtime(
    plugin_root: Path,
    registry: PluginRuntimeRegistry,
) -> Path:
    staged = stage_plugin_runtime(plugin_root, registry)
    backup = activate_plugin_runtime(staged, plugin_root)
    finalize_plugin_runtime(backup)
    return plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
