"""Generate the one plugin-level V4 runtime/build component."""
from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import tempfile
import uuid

from .conversion_codegen import (
    render_cpp_conversion_kernel,
    render_jvm_conversion_kernel,
)
from .cpp_object_runtime_codegen import render_cpp_object_runtime
from .feature_model import PluginRuntimeRegistry
from .templates import render
from .v4_schemas import (
    GENERATED_OWNERSHIP_KIND,
    GENERATED_OWNERSHIP_SCHEMA_VERSION,
)


RUNTIME_RELATIVE_ROOT = Path("android/.supernote-module/v4-runtime")


def generated_runtime_files(registry: PluginRuntimeRegistry) -> dict[str, str]:
    """Return deterministic generated files for one compiled plugin component."""

    feature_rows = "\n".join(
        "    {"
        + json.dumps(entry.feature.feature_id)
        + ", "
        + json.dumps(entry.feature.public_name)
        + "},"
        for entry in registry.features
    )
    if not feature_rows:
        feature_rows = "    // No generated features are currently registered."
    component = registry.component_name
    registration_component = f"{component}_registration"
    source_property = f"supernote.v4.source.{component}.v1"
    generation_count_property = f"supernote.v4.generations.{component}.v1"
    generation_ids_property = f"supernote.v4.generation-ids.{component}.v1"
    binary_registry_prefix = f"supernote.v4.binary.{component}.v1."
    load_request_property = f"supernote.v4.load-request.{component}.v1"
    registrar_property = f"supernote.v4.registrar.{component}.v1"
    jvm_roots = [
        f"local_modules/{entry.feature.npm_name}/{entry.feature.roots.jvm}"
        for entry in registry.features
    ]
    native_roots = [
        f"local_modules/{entry.feature.npm_name}/{entry.feature.roots.native}"
        for entry in registry.features
    ]
    jvm_root_rows = "\n".join(
        f"    new File(supernotePluginRoot, {json.dumps(path)}),"
        for path in jvm_roots
    )
    native_root_rows = "\n".join(
        f"    new File(supernotePluginRoot, {json.dumps(path)}),"
        for path in native_roots
    )
    cmake_native_roots = "\n".join(
        f'    "${{CMAKE_CURRENT_LIST_DIR}}/../../../{path}"'
        for path in native_roots
    )
    consumer_keep_rules = "\n".join(
        f"-keep class {entry.feature.android_namespace}.** {{ *; }}"
        for entry in registry.features
    )
    if consumer_keep_rules:
        consumer_keep_rules += "\n"
    consumer_keep_rules = (
        "# Generated by supernote_module_generator. Do not edit.\n"
        "# JNI resolves these classes and members by generated binary names.\n"
        "# PluginHost casts the generated package through this shared ABI name.\n"
        "-keep interface com.facebook.react.ReactPackage { *; }\n"
        "# The runtime deliberately calls PluginHost's parent-loaded SoLoader API.\n"
        "-keep class com.facebook.soloader.SoLoader { *; }\n"
        "-keep class com.facebook.soloader.SoSource { *; }\n"
        "-keep class com.facebook.soloader.DirectorySoSource { *; }\n"
        "# PluginHost's parent ClassLoader can supply these shared Kotlin ABI classes.\n"
        "-keep class kotlin.** { *; }\n"
        "-keep class kotlinx.coroutines.** { *; }\n"
        "# JNI descriptors include coroutine Job and declared feature types.\n"
        "-keep,includedescriptorclasses class supernote.generated.runtime.** { *; }\n"
        "-keep,includedescriptorclasses class supernote.generated.adapters.** { *; }\n"
        + consumer_keep_rules
    )
    ksp_root_args = "\n".join(
        "    arg("
        + repr(f"supernoteFeatureRoot_{index:08d}")
        + ", "
        + json.dumps(
            f"{entry.feature.feature_id}\tlocal_modules/"
            f"{entry.feature.npm_name}/{entry.feature.roots.jvm}"
        )
        + ")"
        for index, entry in enumerate(registry.features)
    )
    cmake = f"""# Generated by supernote_module_generator. Do not edit.
cmake_minimum_required(VERSION 3.22.1)
project({component} LANGUAGES C CXX)

if(NOT DEFINED SUPERNOTE_VARIANT)
  message(FATAL_ERROR "SUPERNOTE_VARIANT must be debug or release")
endif()

set(SUPERNOTE_NATIVE_ROOTS
{cmake_native_roots}
)
set(SUPERNOTE_USER_SOURCES)
foreach(SUPERNOTE_NATIVE_ROOT IN LISTS SUPERNOTE_NATIVE_ROOTS)
  file(GLOB_RECURSE SUPERNOTE_FEATURE_SOURCES CONFIGURE_DEPENDS
      "${{SUPERNOTE_NATIVE_ROOT}}/*.c"
      "${{SUPERNOTE_NATIVE_ROOT}}/*.cc"
      "${{SUPERNOTE_NATIVE_ROOT}}/*.cpp"
      "${{SUPERNOTE_NATIVE_ROOT}}/*.cxx")
  list(APPEND SUPERNOTE_USER_SOURCES ${{SUPERNOTE_FEATURE_SOURCES}})
endforeach()
set(SUPERNOTE_GENERATED_ROOT "${{CMAKE_CURRENT_LIST_DIR}}/generated")
file(GLOB SUPERNOTE_GENERATED_BINDINGS CONFIGURE_DEPENDS
    "${{SUPERNOTE_GENERATED_ROOT}}/jni/*.cpp")
if(NOT SUPERNOTE_GENERATED_BINDINGS)
  message(FATAL_ERROR "Supernote generated JSI bindings are missing")
endif()

add_library({component} SHARED
    src/feature_registry.cpp
    src/runtime_bootstrap.cpp
    src/runtime_services.cpp
    ${{SUPERNOTE_USER_SOURCES}}
    ${{SUPERNOTE_GENERATED_BINDINGS}}
)

# This dependency-free bridge is loaded from a unique path by each plugin
# ClassLoader. It contains no runtime services; it only enters the one
# process-loaded runtime component so that component can register JNI methods
# on the replacement ClassLoader.
add_library({registration_component} SHARED
    src/runtime_registration_bridge.c
)

find_package(Threads REQUIRED)
find_package(ReactAndroid REQUIRED CONFIG)
find_package(fbjni REQUIRED CONFIG)
target_compile_features({component} PRIVATE cxx_std_23)
set_target_properties(
    {component} PROPERTIES
    C_STANDARD 23
    C_STANDARD_REQUIRED YES
    C_VISIBILITY_PRESET hidden
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN YES)
# JNI and JSI provide many inline C++ member functions as weak definitions.
# A reloadable plugin DSO must bind those definitions to itself; otherwise the
# Android linker may interpose a definition from an older plugin DSO and leave
# a stale function address behind when that DSO is unloaded.
target_link_options({component} PRIVATE "-Wl,-Bsymbolic-functions")
if(SUPERNOTE_V4_WEAK_OBJECT_PROBE)
  target_compile_definitions(
      {component} PRIVATE SUPERNOTE_V4_WEAK_OBJECT_PROBE=1)
endif()
target_include_directories(
    {component} PRIVATE ${{SUPERNOTE_NATIVE_ROOTS}}
    "${{CMAKE_CURRENT_LIST_DIR}}/../../../local_modules"
    "${{CMAKE_CURRENT_LIST_DIR}}/src"
    "${{CMAKE_CURRENT_LIST_DIR}}/include")
target_link_libraries(
    {component} PRIVATE
    Threads::Threads
    ReactAndroid::jsi
    ReactAndroid::reactnative
    fbjni::fbjni
    log)
set_target_properties(
    {registration_component} PROPERTIES
    C_STANDARD 23
    C_STANDARD_REQUIRED YES)
target_link_libraries({registration_component} PRIVATE dl log)
"""
    gradle = f"""// Generated by supernote_module_generator. Do not edit.
plugins {{
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp' version '2.0.21-1.0.28'
}}

def supernotePluginRoot = rootProject.projectDir.parentFile
def supernoteJvmRoots = [
{jvm_root_rows}
]
def supernoteNativeRoots = [
{native_root_rows}
]
def supernoteIsWindows = System.getProperty('os.name').toLowerCase().contains('windows')
def supernoteWeakObjectProbe = providers
    .gradleProperty('supernoteV4WeakObjectProbe')
    .map {{ it.toBoolean() }}
    .orElse(false)
    .get()
def supernoteWindowsBuildRoot = new File(
    System.getProperty('java.io.tmpdir'),
    'supernote-v4/{component}',
)
if (supernoteIsWindows) {{
    layout.buildDirectory.set(new File(supernoteWindowsBuildRoot, 'gradle'))
}}

android {{
    namespace 'supernote.generated.{component}'
    compileSdk rootProject.ext.compileSdkVersion
    ndkVersion rootProject.ext.ndkVersion

    defaultConfig {{
        minSdk rootProject.ext.minSdkVersion
        consumerProguardFiles 'consumer-rules.pro'
        ndk {{
            abiFilters 'arm64-v8a'
        }}
        externalNativeBuild {{
            cmake {{
                arguments(
                    '-DANDROID_STL=c++_shared',
                    "-DSUPERNOTE_V4_WEAK_OBJECT_PROBE=${{supernoteWeakObjectProbe ? 1 : 0}}",
                )
            }}
        }}
    }}

    externalNativeBuild {{
        cmake {{
            path file('CMakeLists.txt')
            version '3.22.1'
            buildStagingDirectory(
                supernoteIsWindows
                    ? new File(supernoteWindowsBuildRoot, 'cxx')
                    : file("${{rootProject.projectDir}}/.cxx/snv4")
            )
        }}
    }}
    buildFeatures {{
        prefab true
    }}
    buildTypes {{
        debug {{
            externalNativeBuild {{
                cmake {{ arguments '-DSUPERNOTE_VARIANT=debug' }}
            }}
        }}
        release {{
            externalNativeBuild {{
                cmake {{ arguments '-DSUPERNOTE_VARIANT=release' }}
            }}
        }}
    }}
    sourceSets {{
        main.java.srcDirs(supernoteJvmRoots)
    }}
    packaging {{
        jniLibs.excludes += [
            '**/libc++_shared.so',
            '**/libfbjni.so',
            '**/libhermes.so',
            '**/libjsi.so',
            '**/libreactnative.so',
        ]
    }}
}}

dependencies {{
    implementation('com.facebook.react:react-android')
    implementation('org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1')
    implementation('org.jspecify:jspecify:1.0.0')
    compileOnly project(':supernote-v4-annotations')
    ksp project(':supernote-v4-processor')
}}

ksp {{
    arg('supernotePluginRoot', supernotePluginRoot.absolutePath)
{ksp_root_args}
}}

kotlin {{
    jvmToolchain(17)
}}

def supernoteModuleCommand = System.getenv('SUPERNOTE_MODULE_COMMAND') ?: 'supernote-module'

['Debug', 'Release'].each {{ buildVariant ->
    def variantName = buildVariant.toLowerCase()
    def stateCheck = tasks.register("checkSupernote${{buildVariant}}State", Exec) {{
        workingDir supernotePluginRoot
        inputs.file(file('feature-registry.json'))
        supernoteNativeRoots.findAll {{ it.isDirectory() }}.each {{ nativeRoot ->
            inputs.dir(nativeRoot)
        }}
        inputs.files(fileTree(layout.buildDirectory.dir(
            "generated/ksp/${{variantName}}/resources"
        )))
        commandLine(
            supernoteModuleCommand,
            '--json',
            'check',
            '--build-hook',
            '--jvm-manifest-root',
            layout.buildDirectory.dir(
                "generated/ksp/${{variantName}}/resources/supernote/generated/manifests"
            ).get().asFile.absolutePath,
        )
    }}
    afterEvaluate {{
        stateCheck.configure {{
            dependsOn tasks.named("ksp${{buildVariant}}Kotlin")
        }}
    }}
    def cmakeBuildType = buildVariant == 'Release' ? 'RelWithDebInfo' : buildVariant
    tasks.matching {{ task ->
        task.name == "externalNativeBuild${{buildVariant}}" ||
            task.name == "configureCMake${{cmakeBuildType}}[arm64-v8a]"
    }}.configureEach {{ dependsOn stateCheck }}
}}
"""
    annotations_gradle = """// Generated by supernote_module_generator. Do not edit.
plugins {
    id 'java-library'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
"""
    processor_gradle = """// Generated by supernote_module_generator. Do not edit.
plugins {
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation project(':supernote-v4-annotations')
    implementation 'com.google.devtools.ksp:symbol-processing-api:2.0.21-1.0.28'
}

kotlin {
    jvmToolchain(17)
}
"""
    header = """// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>

namespace supernote::generated {

struct FeatureDescriptor {
  const char *feature_id;
  const char *public_name;
};

const FeatureDescriptor *feature_registry_data() noexcept;
std::size_t feature_registry_size() noexcept;

}  // namespace supernote::generated
"""
    registry_source = f"""// Generated by supernote_module_generator. Do not edit.
#include "feature_registry.hpp"

#include <array>

namespace supernote::generated {{
namespace {{

constexpr std::array<FeatureDescriptor, {len(registry.features)}> kFeatures{{{{
{feature_rows}
}}}};

}}  // namespace

const FeatureDescriptor *feature_registry_data() noexcept {{
  return kFeatures.data();
}}

std::size_t feature_registry_size() noexcept {{
  return kFeatures.size();
}}

}}  // namespace supernote::generated
"""
    services_header = r"""// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <atomic>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <stdexcept>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>

namespace supernote::runtime {

using SessionId = std::uint64_t;

class CancellationToken {
 public:
  CancellationToken() = default;
  bool is_cancelled() const noexcept;

 private:
  explicit CancellationToken(std::shared_ptr<std::atomic<bool>> state);
  std::shared_ptr<std::atomic<bool>> state_;
  friend class CancellationSource;
};

class CancellationSource {
 public:
  CancellationSource();
  CancellationToken token() const noexcept;
  bool request_cancel() const noexcept;

 private:
  std::shared_ptr<std::atomic<bool>> state_;
};

class BoundedExecutor {
 public:
  using Task = std::function<void(CancellationToken)>;
  using ThreadInitializer =
      std::function<std::function<void()>()>;

  class WorkHandle {
   public:
    WorkHandle() = default;
    bool accepted() const noexcept;
    bool cancel() const noexcept;
    CancellationToken token() const noexcept;

   private:
    struct Control;
    explicit WorkHandle(std::shared_ptr<Control> control);
    std::shared_ptr<Control> control_;
    friend class BoundedExecutor;
  };

  BoundedExecutor(std::size_t worker_count, std::size_t queue_capacity);
  ~BoundedExecutor();
  BoundedExecutor(const BoundedExecutor &) = delete;
  BoundedExecutor &operator=(const BoundedExecutor &) = delete;

  WorkHandle submit(Task task);
  void set_thread_initializer(ThreadInitializer initializer);
  std::size_t thread_count() const noexcept;
  void shutdown() noexcept;

 private:
  struct State;
  void ensure_started();
  std::shared_ptr<State> state_;
};

class DeferredDestruction {
 public:
  explicit DeferredDestruction(std::size_t queue_capacity = 1024);
  ~DeferredDestruction();
  DeferredDestruction(const DeferredDestruction &) = delete;
  DeferredDestruction &operator=(const DeferredDestruction &) = delete;

  bool submit(std::function<void()> cleanup) noexcept;
  template <typename Cleanup>
  bool submit(Cleanup &&cleanup) noexcept {
    try {
      return submit(std::function<void()>(
          std::forward<Cleanup>(cleanup)));
    } catch (...) {
      return false;
    }
  }
  std::size_t thread_count() const noexcept;
  std::size_t queue_depth() const noexcept;
  std::size_t high_water_mark() const noexcept;
  std::uint64_t oldest_item_age_ms() const noexcept;
  std::uint64_t processed_count() const noexcept;
  std::uint64_t failure_count() const noexcept;
  void drain_and_shutdown() noexcept;

 private:
  struct State;
  std::shared_ptr<State> state_;
};

template <typename T>
class ManagedRef {
 public:
  ManagedRef() = default;
  ManagedRef(std::shared_ptr<T> value,
             std::shared_ptr<DeferredDestruction> cleanup)
      : value_(std::move(value)), cleanup_(std::move(cleanup)) {}
  ManagedRef(const ManagedRef &) = default;
  ManagedRef &operator=(const ManagedRef &other) {
    if (this == &other) return *this;
    reset();
    value_ = other.value_;
    cleanup_ = other.cleanup_;
    return *this;
  }
  ManagedRef(ManagedRef &&) noexcept = default;
  ManagedRef &operator=(ManagedRef && other) noexcept {
    if (this == &other) return *this;
    reset();
    value_ = std::move(other.value_);
    cleanup_ = std::move(other.cleanup_);
    return *this;
  }
  ~ManagedRef() { reset(); }

  T *get() const noexcept { return value_.get(); }
  T &operator*() const noexcept { return *value_; }
  T *operator->() const noexcept { return value_.get(); }
  const std::shared_ptr<T> &shared_ref() const noexcept { return value_; }
  explicit operator bool() const noexcept { return static_cast<bool>(value_); }

  void reset() noexcept {
    auto value = std::move(value_);
    auto cleanup = cleanup_;
    cleanup_.reset();
    if (!value) return;
    if (cleanup && cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) return;
    // Queue admission can fail during component shutdown or memory pressure.
    // Inline release is the bounded fallback and cannot touch JSI.
    value.reset();
  }

 private:
  std::shared_ptr<T> value_;
  std::shared_ptr<DeferredDestruction> cleanup_;
};

class FeatureSession;

class RuntimeSession : public std::enable_shared_from_this<RuntimeSession> {
 public:
  using JsTask = std::function<void(void *runtime)>;
  using JsScheduler = std::function<void(JsTask)>;

  static std::shared_ptr<RuntimeSession> create(
      JsScheduler scheduler,
      std::shared_ptr<void> plugin_class_loader = {},
      std::shared_ptr<void> platform_context = {});

  SessionId id() const noexcept;
  bool active() const noexcept;
  bool schedule(JsTask task) noexcept;
  bool invalidate() noexcept;
  std::shared_ptr<void> plugin_class_loader() const noexcept;
  std::shared_ptr<void> platform_context() const noexcept;

 private:
  RuntimeSession(SessionId id, JsScheduler scheduler,
                 std::shared_ptr<void> plugin_class_loader,
                 std::shared_ptr<void> platform_context);
  void cleanup_physical() noexcept;
  void add_feature(const std::shared_ptr<FeatureSession> &feature);
  void remove_feature(SessionId feature_id) noexcept;

  SessionId id_;
  JsScheduler scheduler_;
  std::shared_ptr<void> plugin_class_loader_;
  std::shared_ptr<void> platform_context_;
  std::atomic<bool> active_{true};
  mutable std::mutex mutex_;
  std::unordered_map<SessionId, std::shared_ptr<FeatureSession>> features_;
  friend class FeatureSession;
  friend class ProcessServices;
};

enum class FeatureState { ACTIVE, CLOSING, INACTIVE };
enum class OperationWinner {
  PENDING,
  COMPLETING,
  CANCELLED_BY_FEATURE,
  CANCELLED_BY_RUNTIME,
};

class PendingOperation {
 public:
  using TeardownRejection = std::function<void(void *runtime)>;

  SessionId id() const noexcept;
  OperationWinner winner() const noexcept;
  CancellationToken cancellation_token() const noexcept;
  void set_work(BoundedExecutor::WorkHandle work) noexcept;
  void set_cancel_hook(std::function<void()> hook) noexcept;
  void set_retained_state(std::shared_ptr<void> state) noexcept;
  std::shared_ptr<void> take_internal_completion() noexcept;

 private:
  PendingOperation(SessionId id, TeardownRejection rejection,
                   std::shared_ptr<void> internal_completion = {});
  bool claim(OperationWinner winner) noexcept;
  TeardownRejection take_rejection() noexcept;

  SessionId id_;
  std::atomic<OperationWinner> winner_{OperationWinner::PENDING};
  CancellationSource cancellation_;
  std::mutex mutex_;
  BoundedExecutor::WorkHandle work_;
  std::function<void()> cancel_hook_;
  std::shared_ptr<void> retained_state_;
  std::shared_ptr<void> internal_completion_;
  TeardownRejection rejection_;
  friend class FeatureSession;
};

class FeatureSession : public std::enable_shared_from_this<FeatureSession> {
 public:
  static std::shared_ptr<FeatureSession> create(
      const std::shared_ptr<RuntimeSession> &runtime,
      std::shared_ptr<DeferredDestruction> cleanup);

  SessionId id() const noexcept;
  FeatureState state() const noexcept;
  std::shared_ptr<RuntimeSession> runtime() const noexcept;
  std::shared_ptr<PendingOperation> accept(
      PendingOperation::TeardownRejection rejection,
      std::shared_ptr<void> internal_completion = {});
  std::shared_ptr<PendingOperation> accept_factory(
      std::function<PendingOperation::TeardownRejection(SessionId)> factory);
  bool schedule_completion(
      const std::shared_ptr<PendingOperation> &operation,
      RuntimeSession::JsTask completion) noexcept;
  bool claim_internal_completion(
      const std::shared_ptr<PendingOperation> &operation) noexcept;
  void close_feature() noexcept;
  void close_runtime() noexcept;

  template <typename T, typename Factory>
  ManagedRef<T> service(const std::string &declaration_id,
                        Factory &&factory) {
    static_assert(std::is_invocable_r_v<std::shared_ptr<T>, Factory>);
    std::shared_ptr<ServiceSlot> slot;
    std::uint64_t attempt = 0;
    {
      std::unique_lock lock(mutex_);
      if (state_.load(std::memory_order_acquire) != FeatureState::ACTIVE) {
        throw std::runtime_error("feature session is closed");
      }
      auto &stored = services_[declaration_id];
      if (!stored) stored = std::make_shared<ServiceSlot>();
      slot = stored;
    }
    {
      std::unique_lock lock(slot->mutex);
      if (slot->value) {
        return ManagedRef<T>(std::static_pointer_cast<T>(slot->value), cleanup_);
      }
      if (slot->initializing) {
        attempt = slot->attempt;
        slot->ready.wait(lock, [&] { return !slot->initializing; });
        if (slot->value) {
          return ManagedRef<T>(std::static_pointer_cast<T>(slot->value), cleanup_);
        }
        if (slot->completed_attempt == attempt && slot->failure) {
          std::rethrow_exception(slot->failure);
        }
      }
      slot->initializing = true;
      attempt = ++slot->attempt;
      slot->failure = nullptr;
    }
    try {
      auto created = std::invoke(std::forward<Factory>(factory));
      if (!created) throw std::runtime_error("service factory returned null");
      {
        std::unique_lock feature_lock(mutex_);
        std::unique_lock slot_lock(slot->mutex);
        if (state_.load(std::memory_order_acquire) != FeatureState::ACTIVE) {
          slot->initializing = false;
          slot->completed_attempt = attempt;
          slot->failure = std::make_exception_ptr(
              std::runtime_error("feature closed during service construction"));
          slot->ready.notify_all();
          defer_release(std::move(created));
          std::rethrow_exception(slot->failure);
        }
        slot->value = created;
        slot->initializing = false;
        slot->completed_attempt = attempt;
        slot->ready.notify_all();
      }
      return ManagedRef<T>(std::move(created), cleanup_);
    } catch (...) {
      std::unique_lock lock(slot->mutex);
      if (slot->initializing && slot->attempt == attempt) {
        slot->initializing = false;
        slot->completed_attempt = attempt;
        slot->failure = std::current_exception();
        slot->ready.notify_all();
      }
      throw;
    }
  }

 private:
  struct ServiceSlot {
    std::mutex mutex;
    std::condition_variable ready;
    bool initializing = false;
    std::uint64_t attempt = 0;
    std::uint64_t completed_attempt = 0;
    std::shared_ptr<void> value;
    std::exception_ptr failure;
  };

  FeatureSession(SessionId id, std::shared_ptr<RuntimeSession> runtime,
                 std::shared_ptr<DeferredDestruction> cleanup);
  void close(bool runtime_teardown) noexcept;
  void erase_pending(SessionId operation_id) noexcept;

  template <typename T>
  void defer_release(std::shared_ptr<T> value) noexcept {
    if (!value) return;
    auto cleanup = cleanup_;
    if (cleanup && cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) return;
    value.reset();
  }

  SessionId id_;
  std::weak_ptr<RuntimeSession> runtime_;
  std::shared_ptr<DeferredDestruction> cleanup_;
  std::atomic<FeatureState> state_{FeatureState::ACTIVE};
  mutable std::mutex mutex_;
  std::unordered_map<SessionId, std::shared_ptr<PendingOperation>> pending_;
  std::unordered_map<std::string, std::shared_ptr<ServiceSlot>> services_;
};

class FeatureCallScope {
 public:
  explicit FeatureCallScope(std::shared_ptr<FeatureSession> feature) noexcept;
  ~FeatureCallScope();
  FeatureCallScope(const FeatureCallScope &) = delete;
  FeatureCallScope &operator=(const FeatureCallScope &) = delete;

 private:
  std::weak_ptr<FeatureSession> previous_;
};

std::shared_ptr<FeatureSession> current_feature_session() noexcept;

class ProcessServices {
 public:
  using JvmAsyncCompletion =
      std::function<void(void *environment, void *result,
                         std::string error_code, std::string failure)>;

  ProcessServices();
  ~ProcessServices();
  ProcessServices(const ProcessServices &) = delete;
  ProcessServices &operator=(const ProcessServices &) = delete;

  BoundedExecutor &workers() noexcept;
  void configure_worker_threads(
      BoundedExecutor::ThreadInitializer initializer);
  std::shared_ptr<DeferredDestruction> cleanup() const noexcept;
  void set_java_vm(void *java_vm) noexcept;
  void *java_vm() const noexcept;
  SessionId register_jvm_async_completion(JvmAsyncCompletion completion);
  bool discard_jvm_async_completion(SessionId completion_id) noexcept;
  void complete_jvm_async(SessionId completion_id, void *environment,
                          void *result, std::string error_code,
                          std::string failure) noexcept;
  std::size_t thread_count() const noexcept;
  bool retire_runtime(std::shared_ptr<RuntimeSession> runtime) noexcept;
  std::size_t retired_runtime_count() const noexcept;
  bool restart_required() const noexcept;
  void shutdown() noexcept;

 private:
  bool try_schedule_retired_runtime(SessionId id) noexcept;
  bool ensure_retirement_retry_worker() noexcept;
  void retirement_retry_loop() noexcept;
  BoundedExecutor workers_;
  std::shared_ptr<DeferredDestruction> cleanup_;
  std::atomic<void *> java_vm_{nullptr};
  std::mutex jvm_async_mutex_;
  std::unordered_map<SessionId, JvmAsyncCompletion> jvm_async_completions_;
  mutable std::mutex retired_runtime_mutex_;
  std::unordered_map<SessionId, std::shared_ptr<RuntimeSession>> retired_runtimes_;
  std::unordered_set<SessionId> scheduled_retirements_;
  std::condition_variable retirement_ready_;
  std::thread retirement_retry_worker_;
  bool retirement_stopping_ = false;
  std::atomic<bool> restart_required_{false};
};

ProcessServices &process_services() noexcept;

}  // namespace supernote::runtime
"""
    public_runtime_header = r"""// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <stdexcept>
#include <string>
#include <utility>
#include <variant>

namespace supernote {

enum class ErrorCode {
  RESOURCE_EXHAUSTED,
  CANCELLED,
  FEATURE_CLOSED,
  IMPLEMENTATION_ERROR,
  INTERNAL,
};

class Error final : public std::runtime_error {
 public:
  Error(ErrorCode code, std::string message)
      : std::runtime_error(std::move(message)), code_(code) {}
  ErrorCode code() const noexcept { return code_; }

 private:
  ErrorCode code_;
};

template <typename T>
class Result final {
 public:
  static Result success(T value) {
    return Result(std::in_place_index<0>, std::move(value));
  }
  static Result failure(Error error) {
    return Result(std::in_place_index<1>, std::move(error));
  }
  explicit operator bool() const noexcept { return value_.index() == 0; }
  T &value() & { return std::get<0>(value_); }
  const T &value() const & { return std::get<0>(value_); }
  T &&value() && { return std::get<0>(std::move(value_)); }
  Error &error() & { return std::get<1>(value_); }
  const Error &error() const & { return std::get<1>(value_); }

 private:
  template <std::size_t Index, typename Value>
  Result(std::in_place_index_t<Index> index, Value value)
      : value_(index, std::move(value)) {}
  std::variant<T, Error> value_;
};

template <>
class Result<void> final {
 public:
  static Result success() { return Result(); }
  static Result failure(Error error) { return Result(std::move(error)); }
  explicit operator bool() const noexcept { return success_; }
  void value() const {
    if (!success_) throw std::logic_error("Supernote result has no value");
  }
  Error &error() & { return error_; }
  const Error &error() const & { return error_; }

 private:
  Result() : success_(true), error_(ErrorCode::INTERNAL, "no error") {}
  explicit Result(Error error) : success_(false), error_(std::move(error)) {}
  bool success_;
  Error error_;
};

}  // namespace supernote
"""
    services = r"""// Generated by supernote_module_generator. Do not edit.
#include "runtime_services.hpp"

#include <algorithm>
#include <chrono>
#include <deque>
#include <stdexcept>
#include <thread>
#include <utility>
#include <vector>

namespace supernote::runtime {
namespace {

std::atomic<SessionId> next_session_id{1};

SessionId allocate_session_id() noexcept {
  return next_session_id.fetch_add(1, std::memory_order_relaxed);
}

}  // namespace

CancellationToken::CancellationToken(
    std::shared_ptr<std::atomic<bool>> state) : state_(std::move(state)) {}

bool CancellationToken::is_cancelled() const noexcept {
  return state_ && state_->load(std::memory_order_acquire);
}

CancellationSource::CancellationSource()
    : state_(std::make_shared<std::atomic<bool>>(false)) {}

CancellationToken CancellationSource::token() const noexcept {
  return CancellationToken(state_);
}

bool CancellationSource::request_cancel() const noexcept {
  return state_ && !state_->exchange(true, std::memory_order_acq_rel);
}

struct BoundedExecutor::WorkHandle::Control {
  std::uint64_t id = 0;
  CancellationSource cancellation;
  std::function<bool(std::uint64_t)> cancel_queued;
  bool accepted = false;
};

struct BoundedExecutor::State {
  struct Item {
    std::uint64_t id;
    CancellationSource cancellation;
    Task task;
  };

  State(std::size_t worker_count, std::size_t capacity)
      : worker_count(worker_count), capacity(capacity) {}
  std::mutex mutex;
  std::condition_variable ready;
  std::deque<Item> queue;
  std::vector<std::thread> workers;
  std::size_t worker_count;
  std::size_t capacity;
  std::atomic<std::size_t> live_workers{0};
  std::uint64_t next_id = 1;
  ThreadInitializer thread_initializer;
  bool stopped = false;
};

BoundedExecutor::WorkHandle::WorkHandle(std::shared_ptr<Control> control)
    : control_(std::move(control)) {}

bool BoundedExecutor::WorkHandle::accepted() const noexcept {
  return control_ && control_->accepted;
}

bool BoundedExecutor::WorkHandle::cancel() const noexcept {
  if (!control_) return false;
  control_->cancellation.request_cancel();
  return control_->cancel_queued && control_->cancel_queued(control_->id);
}

CancellationToken BoundedExecutor::WorkHandle::token() const noexcept {
  return control_ ? control_->cancellation.token() : CancellationToken{};
}

BoundedExecutor::BoundedExecutor(std::size_t worker_count,
                                 std::size_t queue_capacity)
    : state_(std::make_shared<State>(worker_count, queue_capacity)) {
  if (worker_count == 0 || queue_capacity == 0) {
    throw std::invalid_argument("executor size and capacity must be positive");
  }
}

void BoundedExecutor::ensure_started() {
  auto state = state_;
  std::lock_guard lock(state->mutex);
  if (state->stopped) {
    throw std::runtime_error("executor is stopped");
  }
  if (!state->workers.empty()) return;
  state->workers.reserve(state->worker_count);
  for (std::size_t index = 0; index < state->worker_count; ++index) {
    state_->workers.emplace_back([state = state_] {
      state->live_workers.fetch_add(1, std::memory_order_acq_rel);
      bool thread_initialized = false;
      std::function<void()> thread_cleanup;
      while (true) {
        State::Item item;
        {
          std::unique_lock lock(state->mutex);
          state->ready.wait(lock, [&] {
            return state->stopped || !state->queue.empty();
          });
          if (state->queue.empty()) {
            if (state->stopped) break;
            continue;
          }
          item = std::move(state->queue.front());
          state->queue.pop_front();
        }
        if (!thread_initialized) {
          ThreadInitializer initializer;
          {
            std::lock_guard lock(state->mutex);
            initializer = state->thread_initializer;
          }
          if (initializer) {
            try {
              thread_cleanup = initializer();
              thread_initialized = true;
            } catch (...) {
              // A later task may retry initialization. The current task still
              // owns its normal error/completion path.
            }
          }
        }
        if (item.cancellation.token().is_cancelled()) continue;
        try {
          item.task(item.cancellation.token());
        } catch (...) {
          // Generated completion paths translate failures. An escaping task
          // must never terminate the shared executor.
        }
      }
      if (thread_cleanup) {
        try { thread_cleanup(); } catch (...) {}
      }
      state->live_workers.fetch_sub(1, std::memory_order_acq_rel);
    });
  }
}

BoundedExecutor::~BoundedExecutor() { shutdown(); }

BoundedExecutor::WorkHandle BoundedExecutor::submit(Task task) {
  if (!task) return {};
  ensure_started();
  auto control = std::make_shared<WorkHandle::Control>();
  auto state = state_;
  {
    std::lock_guard lock(state->mutex);
    if (state->stopped || state->queue.size() >= state->capacity) {
      return WorkHandle(control);
    }
    control->id = state->next_id++;
    control->accepted = true;
    state->queue.push_back(
        {control->id, control->cancellation, std::move(task)});
  }
  control->cancel_queued = [weak = std::weak_ptr<State>(state)](
                               std::uint64_t id) {
    auto locked = weak.lock();
    if (!locked) return false;
    std::lock_guard guard(locked->mutex);
    auto found = std::find_if(
        locked->queue.begin(), locked->queue.end(),
        [id](const State::Item &item) { return item.id == id; });
    if (found == locked->queue.end()) return false;
    locked->queue.erase(found);
    return true;
  };
  state->ready.notify_one();
  return WorkHandle(std::move(control));
}

void BoundedExecutor::set_thread_initializer(
    ThreadInitializer initializer) {
  if (!initializer) {
    throw std::invalid_argument("worker thread initializer is required");
  }
  auto state = state_;
  std::lock_guard lock(state->mutex);
  if (state->stopped) {
    throw std::runtime_error("executor is stopped");
  }
  state->thread_initializer = std::move(initializer);
}

std::size_t BoundedExecutor::thread_count() const noexcept {
  auto state = state_;
  return state
      ? state->live_workers.load(std::memory_order_acquire)
      : 0;
}

void BoundedExecutor::shutdown() noexcept {
  auto state = state_;
  if (!state) return;
  {
    std::lock_guard lock(state->mutex);
    if (state->stopped) return;
    state->stopped = true;
    for (auto &item : state->queue) item.cancellation.request_cancel();
    state->queue.clear();
  }
  state->ready.notify_all();
  for (auto &worker : state->workers) {
    if (worker.joinable()) worker.join();
  }
  state->workers.clear();
}

struct DeferredDestruction::State {
  struct Item {
    std::chrono::steady_clock::time_point enqueued;
    std::function<void()> cleanup;
  };

  explicit State(std::size_t requested_capacity) : capacity(requested_capacity) {}
  std::mutex mutex;
  std::condition_variable ready;
  std::deque<Item> queue;
  std::thread worker;
  std::atomic<std::size_t> live_workers{0};
  const std::size_t capacity;
  std::atomic<std::size_t> high_water{0};
  std::atomic<std::uint64_t> processed{0};
  std::atomic<std::uint64_t> failures{0};
  bool stopping = false;
};

DeferredDestruction::DeferredDestruction(std::size_t queue_capacity)
    : state_(std::make_shared<State>(queue_capacity)) {
  if (queue_capacity == 0) {
    throw std::invalid_argument("deferred destruction capacity must be positive");
  }
}

DeferredDestruction::~DeferredDestruction() { drain_and_shutdown(); }

bool DeferredDestruction::submit(std::function<void()> cleanup) noexcept {
  if (!cleanup) return true;
  auto state = state_;
  try {
    {
      std::lock_guard lock(state->mutex);
      if (state->stopping) return false;
      if (state->queue.size() >= state->capacity) return false;
      if (!state->worker.joinable()) {
        state->worker = std::thread([state] {
          state->live_workers.fetch_add(1, std::memory_order_acq_rel);
          while (true) {
            State::Item item;
            {
              std::unique_lock worker_lock(state->mutex);
              state->ready.wait(worker_lock, [&] {
                return state->stopping || !state->queue.empty();
              });
              if (state->queue.empty() && state->stopping) break;
              item = std::move(state->queue.front());
              state->queue.pop_front();
            }
            try {
              item.cleanup();
              state->processed.fetch_add(1, std::memory_order_acq_rel);
            } catch (...) {
              state->failures.fetch_add(1, std::memory_order_acq_rel);
              // Cleanup never crosses into JSI and never stops the facility.
            }
          }
          state->live_workers.fetch_sub(1, std::memory_order_acq_rel);
        });
      }
      state->queue.push_back(
          {std::chrono::steady_clock::now(), std::move(cleanup)});
      const auto depth = state->queue.size();
      auto previous = state->high_water.load(std::memory_order_acquire);
      while (depth > previous &&
             !state->high_water.compare_exchange_weak(
                 previous, depth, std::memory_order_acq_rel)) {}
    }
    state->ready.notify_one();
    return true;
  } catch (...) {
    return false;
  }
}

std::size_t DeferredDestruction::thread_count() const noexcept {
  auto state = state_;
  return state
      ? state->live_workers.load(std::memory_order_acquire)
      : 0;
}

std::size_t DeferredDestruction::queue_depth() const noexcept {
  auto state = state_;
  if (!state) return 0;
  std::lock_guard lock(state->mutex);
  return state->queue.size();
}

std::size_t DeferredDestruction::high_water_mark() const noexcept {
  return state_ ? state_->high_water.load(std::memory_order_acquire) : 0;
}

std::uint64_t DeferredDestruction::oldest_item_age_ms() const noexcept {
  auto state = state_;
  if (!state) return 0;
  std::lock_guard lock(state->mutex);
  if (state->queue.empty()) return 0;
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::milliseconds>(
          std::chrono::steady_clock::now() - state->queue.front().enqueued)
          .count());
}

std::uint64_t DeferredDestruction::processed_count() const noexcept {
  return state_ ? state_->processed.load(std::memory_order_acquire) : 0;
}

std::uint64_t DeferredDestruction::failure_count() const noexcept {
  return state_ ? state_->failures.load(std::memory_order_acquire) : 0;
}

void DeferredDestruction::drain_and_shutdown() noexcept {
  auto state = state_;
  if (!state) return;
  {
    std::lock_guard lock(state->mutex);
    state->stopping = true;
  }
  state->ready.notify_all();
  if (state->worker.joinable()) state->worker.join();
}

RuntimeSession::RuntimeSession(SessionId id, JsScheduler scheduler,
                               std::shared_ptr<void> plugin_class_loader,
                               std::shared_ptr<void> platform_context)
    : id_(id),
      scheduler_(std::move(scheduler)),
      plugin_class_loader_(std::move(plugin_class_loader)),
      platform_context_(std::move(platform_context)) {}

std::shared_ptr<RuntimeSession> RuntimeSession::create(
    JsScheduler scheduler, std::shared_ptr<void> plugin_class_loader,
    std::shared_ptr<void> platform_context) {
  if (!scheduler) throw std::invalid_argument("JS scheduler is required");
  // Construct bounded process-lifetime infrastructure before user work can
  // inject allocation failures into invalidation.
  (void)process_services();
  return std::shared_ptr<RuntimeSession>(new RuntimeSession(
      allocate_session_id(), std::move(scheduler),
      std::move(plugin_class_loader), std::move(platform_context)));
}

SessionId RuntimeSession::id() const noexcept { return id_; }

bool RuntimeSession::active() const noexcept {
  return active_.load(std::memory_order_acquire);
}

bool RuntimeSession::schedule(JsTask task) noexcept {
  if (!task || !active()) return false;
  auto weak = weak_from_this();
  const auto expected = id_;
  JsScheduler scheduler;
  {
    std::lock_guard lock(mutex_);
    if (!active() || !scheduler_) return false;
    scheduler = scheduler_;
  }
  try {
    scheduler([weak, expected, task = std::move(task)](void *runtime) mutable {
      auto session = weak.lock();
      if (!session || session->id_ != expected || !session->active() ||
          runtime == nullptr) {
        return;
      }
      task(runtime);
    });
    return true;
  } catch (...) {
    return false;
  }
}

void RuntimeSession::add_feature(
    const std::shared_ptr<FeatureSession> &feature) {
  std::lock_guard lock(mutex_);
  if (!active()) throw std::runtime_error(
      "SNV4_SESSION_INVALIDATED: runtime session is inactive");
  features_[feature->id()] = feature;
}

void RuntimeSession::remove_feature(SessionId feature_id) noexcept {
  std::lock_guard lock(mutex_);
  features_.erase(feature_id);
}

bool RuntimeSession::invalidate() noexcept {
  active_.store(false, std::memory_order_release);
  try {
    return process_services().retire_runtime(shared_from_this());
  } catch (...) {
    return false;
  }
}

void RuntimeSession::cleanup_physical() noexcept {
  {
    std::lock_guard lock(mutex_);
    plugin_class_loader_.reset();
    platform_context_.reset();
    scheduler_ = {};
  }
  for (;;) {
    std::shared_ptr<FeatureSession> feature;
    {
      std::lock_guard lock(mutex_);
      if (features_.empty()) break;
      auto current = features_.begin();
      feature = std::move(current->second);
      features_.erase(current);
    }
    feature->close_runtime();
  }
}

std::shared_ptr<void> RuntimeSession::plugin_class_loader() const noexcept {
  std::lock_guard lock(mutex_);
  return plugin_class_loader_;
}

std::shared_ptr<void> RuntimeSession::platform_context() const noexcept {
  std::lock_guard lock(mutex_);
  return platform_context_;
}

PendingOperation::PendingOperation(
    SessionId id, TeardownRejection rejection,
    std::shared_ptr<void> internal_completion)
    : id_(id),
      internal_completion_(std::move(internal_completion)),
      rejection_(std::move(rejection)) {}

SessionId PendingOperation::id() const noexcept { return id_; }

OperationWinner PendingOperation::winner() const noexcept {
  return winner_.load(std::memory_order_acquire);
}

CancellationToken PendingOperation::cancellation_token() const noexcept {
  return cancellation_.token();
}

void PendingOperation::set_work(BoundedExecutor::WorkHandle work) noexcept {
  std::lock_guard lock(mutex_);
  work_ = std::move(work);
  if (winner() != OperationWinner::PENDING) work_.cancel();
}

void PendingOperation::set_cancel_hook(std::function<void()> hook) noexcept {
  if (!hook) return;
  bool run_now = false;
  {
    std::lock_guard lock(mutex_);
    const auto current = winner();
    if (current == OperationWinner::PENDING) {
      cancel_hook_ = std::move(hook);
      return;
    }
    run_now = current == OperationWinner::CANCELLED_BY_FEATURE ||
        current == OperationWinner::CANCELLED_BY_RUNTIME;
  }
  if (run_now) {
    try { hook(); } catch (...) {}
  }
}

void PendingOperation::set_retained_state(std::shared_ptr<void> state) noexcept {
  std::lock_guard lock(mutex_);
  retained_state_ = std::move(state);
}

std::shared_ptr<void> PendingOperation::take_internal_completion() noexcept {
  std::lock_guard lock(mutex_);
  return std::move(internal_completion_);
}

bool PendingOperation::claim(OperationWinner winner) noexcept {
  auto expected = OperationWinner::PENDING;
  if (!winner_.compare_exchange_strong(expected, winner,
                                       std::memory_order_acq_rel)) {
    return false;
  }
  if (winner == OperationWinner::CANCELLED_BY_FEATURE ||
      winner == OperationWinner::CANCELLED_BY_RUNTIME) {
    cancellation_.request_cancel();
    std::function<void()> hook;
    {
      std::lock_guard lock(mutex_);
      work_.cancel();
      hook = std::move(cancel_hook_);
    }
    if (hook) {
      try { hook(); } catch (...) {}
    }
  } else if (winner == OperationWinner::COMPLETING) {
    std::lock_guard lock(mutex_);
    cancel_hook_ = {};
  }
  return true;
}

PendingOperation::TeardownRejection PendingOperation::take_rejection() noexcept {
  std::lock_guard lock(mutex_);
  return std::move(rejection_);
}

FeatureSession::FeatureSession(SessionId id,
                               std::shared_ptr<RuntimeSession> runtime,
                               std::shared_ptr<DeferredDestruction> cleanup)
    : id_(id), runtime_(std::move(runtime)), cleanup_(std::move(cleanup)) {}

std::shared_ptr<FeatureSession> FeatureSession::create(
    const std::shared_ptr<RuntimeSession> &runtime,
    std::shared_ptr<DeferredDestruction> cleanup) {
  if (!runtime || !runtime->active()) {
    throw std::invalid_argument("active runtime session is required");
  }
  if (!cleanup) throw std::invalid_argument("cleanup facility is required");
  auto feature = std::shared_ptr<FeatureSession>(new FeatureSession(
      allocate_session_id(), runtime, std::move(cleanup)));
  runtime->add_feature(feature);
  return feature;
}

SessionId FeatureSession::id() const noexcept { return id_; }

FeatureState FeatureSession::state() const noexcept {
  return state_.load(std::memory_order_acquire);
}

std::shared_ptr<RuntimeSession> FeatureSession::runtime() const noexcept {
  std::lock_guard lock(mutex_);
  return runtime_.lock();
}

std::shared_ptr<PendingOperation> FeatureSession::accept(
    PendingOperation::TeardownRejection rejection,
    std::shared_ptr<void> internal_completion) {
  std::lock_guard lock(mutex_);
  auto runtime = runtime_.lock();
  if (state() != FeatureState::ACTIVE || !runtime || !runtime->active()) {
    return {};
  }
  auto operation = std::shared_ptr<PendingOperation>(
      new PendingOperation(
          allocate_session_id(), std::move(rejection),
          std::move(internal_completion)));
  pending_.emplace(operation->id(), operation);
  return operation;
}

std::shared_ptr<PendingOperation> FeatureSession::accept_factory(
    std::function<PendingOperation::TeardownRejection(SessionId)> factory) {
  std::lock_guard lock(mutex_);
  auto runtime = runtime_.lock();
  if (!factory || state() != FeatureState::ACTIVE || !runtime ||
      !runtime->active()) {
    return {};
  }
  const auto id = allocate_session_id();
  auto operation = std::shared_ptr<PendingOperation>(
      new PendingOperation(id, factory(id)));
  pending_.emplace(operation->id(), operation);
  return operation;
}

bool FeatureSession::schedule_completion(
    const std::shared_ptr<PendingOperation> &operation,
    RuntimeSession::JsTask completion) noexcept {
  if (!operation || !completion) return false;
  std::shared_ptr<RuntimeSession> runtime;
  {
    std::lock_guard lock(mutex_);
    if (state() != FeatureState::ACTIVE) return false;
    runtime = runtime_.lock();
    if (!runtime || !runtime->active()) return false;
  }
  auto weak = weak_from_this();
  const auto expected_feature = id_;
  return runtime->schedule(
      [weak, expected_feature, operation,
       completion = std::move(completion)](void *js_runtime) mutable {
        auto feature = weak.lock();
        if (!feature || feature->id_ != expected_feature) return;
        {
          std::lock_guard lock(feature->mutex_);
          if (feature->state() != FeatureState::ACTIVE ||
              !operation->claim(OperationWinner::COMPLETING)) {
            return;
          }
          feature->pending_.erase(operation->id());
        }
        operation->take_rejection();
        completion(js_runtime);
      });
}

bool FeatureSession::claim_internal_completion(
    const std::shared_ptr<PendingOperation> &operation) noexcept {
  if (!operation) return false;
  std::lock_guard lock(mutex_);
  if (state() != FeatureState::ACTIVE ||
      !operation->claim(OperationWinner::COMPLETING)) {
    return false;
  }
  pending_.erase(operation->id());
  operation->take_rejection();
  return true;
}

void FeatureSession::close_feature() noexcept { close(false); }

void FeatureSession::close_runtime() noexcept { close(true); }

void FeatureSession::close(bool runtime_teardown) noexcept {
  std::shared_ptr<RuntimeSession> runtime;
  {
    std::lock_guard lock(mutex_);
    if (state() != FeatureState::ACTIVE) return;
    state_.store(FeatureState::CLOSING, std::memory_order_release);
    runtime = runtime_.lock();
  }

  if (!runtime_teardown && runtime) runtime->remove_feature(id_);
  for (;;) {
    std::shared_ptr<PendingOperation> operation;
    {
      std::lock_guard lock(mutex_);
      if (pending_.empty()) break;
      auto current = pending_.begin();
      operation = std::move(current->second);
      pending_.erase(current);
    }
    const auto outcome = runtime_teardown
        ? OperationWinner::CANCELLED_BY_RUNTIME
        : OperationWinner::CANCELLED_BY_FEATURE;
    if (!operation->claim(outcome)) continue;
    auto internal_completion = operation->take_internal_completion();
    if (internal_completion) {
      defer_release(std::move(internal_completion));
    }
    auto rejection = operation->take_rejection();
    if (!runtime_teardown && runtime && runtime->active() && rejection) {
      runtime->schedule(std::move(rejection));
    }
  }
  for (;;) {
    std::shared_ptr<ServiceSlot> slot;
    {
      std::lock_guard lock(mutex_);
      if (services_.empty()) break;
      auto current = services_.begin();
      slot = std::move(current->second);
      services_.erase(current);
    }
    std::shared_ptr<void> service;
    {
      std::lock_guard slot_lock(slot->mutex);
      service = std::move(slot->value);
    }
    defer_release(std::move(service));
  }
  {
    std::lock_guard lock(mutex_);
    runtime_.reset();
    state_.store(FeatureState::INACTIVE, std::memory_order_release);
  }
}

void FeatureSession::erase_pending(SessionId operation_id) noexcept {
  std::lock_guard lock(mutex_);
  pending_.erase(operation_id);
}

namespace {
thread_local std::weak_ptr<FeatureSession> g_current_feature;
}

FeatureCallScope::FeatureCallScope(
    std::shared_ptr<FeatureSession> feature) noexcept
    : previous_(g_current_feature) {
  g_current_feature = feature;
}

FeatureCallScope::~FeatureCallScope() {
  g_current_feature = previous_;
}

std::shared_ptr<FeatureSession> current_feature_session() noexcept {
  return g_current_feature.lock();
}

ProcessServices::ProcessServices()
    : workers_(std::max<std::size_t>(1, std::thread::hardware_concurrency()),
               256),
      cleanup_(std::make_shared<DeferredDestruction>()) {}

ProcessServices::~ProcessServices() { shutdown(); }

BoundedExecutor &ProcessServices::workers() noexcept { return workers_; }

void ProcessServices::configure_worker_threads(
    BoundedExecutor::ThreadInitializer initializer) {
  workers_.set_thread_initializer(std::move(initializer));
}

std::shared_ptr<DeferredDestruction> ProcessServices::cleanup() const noexcept {
  return cleanup_;
}

void ProcessServices::set_java_vm(void *java_vm) noexcept {
  java_vm_.store(java_vm, std::memory_order_release);
}

void *ProcessServices::java_vm() const noexcept {
  return java_vm_.load(std::memory_order_acquire);
}

SessionId ProcessServices::register_jvm_async_completion(
    JvmAsyncCompletion completion) {
  if (!completion) {
    throw std::invalid_argument("JVM async completion is required");
  }
  const auto id = allocate_session_id();
  std::lock_guard lock(jvm_async_mutex_);
  jvm_async_completions_.emplace(id, std::move(completion));
  return id;
}

bool ProcessServices::discard_jvm_async_completion(
    SessionId completion_id) noexcept {
  std::lock_guard lock(jvm_async_mutex_);
  return jvm_async_completions_.erase(completion_id) != 0;
}

void ProcessServices::complete_jvm_async(
    SessionId completion_id,
    void *environment,
    void *result,
    std::string error_code,
    std::string failure) noexcept {
  JvmAsyncCompletion completion;
  {
    std::lock_guard lock(jvm_async_mutex_);
    auto found = jvm_async_completions_.find(completion_id);
    if (found == jvm_async_completions_.end()) return;
    completion = std::move(found->second);
    jvm_async_completions_.erase(found);
  }
  try {
    completion(environment, result, std::move(error_code), std::move(failure));
  } catch (...) {
    // Native-async completion must never unwind through JNI/coroutine code.
  }
}

bool ProcessServices::retire_runtime(
    std::shared_ptr<RuntimeSession> runtime) noexcept {
  if (!runtime) return true;
  try {
    constexpr std::size_t kRetiredRuntimeLimit = 32;
    const auto id = runtime->id();
    {
      std::lock_guard lock(retired_runtime_mutex_);
      if (retired_runtimes_.find(id) == retired_runtimes_.end()) {
        if (retired_runtimes_.size() >= kRetiredRuntimeLimit) {
          restart_required_.store(true, std::memory_order_release);
          return false;
        }
        retired_runtimes_.emplace(id, std::move(runtime));
      }
    }
    if (!try_schedule_retired_runtime(id) &&
        !ensure_retirement_retry_worker()) {
      return false;
    }
    return true;
  } catch (...) {
    restart_required_.store(true, std::memory_order_release);
    return false;
  }
}

bool ProcessServices::try_schedule_retired_runtime(SessionId id) noexcept {
  try {
    {
      std::lock_guard lock(retired_runtime_mutex_);
      if (retired_runtimes_.find(id) == retired_runtimes_.end() ||
          scheduled_retirements_.find(id) != scheduled_retirements_.end()) {
        return true;
      }
      scheduled_retirements_.insert(id);
    }
    const auto accepted = cleanup_ && cleanup_->submit([this, id] {
      std::shared_ptr<RuntimeSession> retired;
      {
        std::lock_guard lock(retired_runtime_mutex_);
        scheduled_retirements_.erase(id);
        auto found = retired_runtimes_.find(id);
        if (found == retired_runtimes_.end()) return;
        retired = std::move(found->second);
        retired_runtimes_.erase(found);
      }
      retired->cleanup_physical();
      retirement_ready_.notify_all();
    });
    if (accepted) return true;
    {
      std::lock_guard lock(retired_runtime_mutex_);
      scheduled_retirements_.erase(id);
    }
    return false;
  } catch (...) {
    std::lock_guard lock(retired_runtime_mutex_);
    scheduled_retirements_.erase(id);
    return false;
  }
}

bool ProcessServices::ensure_retirement_retry_worker() noexcept {
  try {
    {
      std::lock_guard lock(retired_runtime_mutex_);
      if (retirement_stopping_) {
        restart_required_.store(true, std::memory_order_release);
        return false;
      }
      if (!retirement_retry_worker_.joinable()) {
        retirement_retry_worker_ =
            std::thread([this] { retirement_retry_loop(); });
      }
    }
    retirement_ready_.notify_one();
    return true;
  } catch (...) {
    restart_required_.store(true, std::memory_order_release);
    return false;
  }
}

void ProcessServices::retirement_retry_loop() noexcept {
  while (true) {
    SessionId candidate = 0;
    {
      std::unique_lock lock(retired_runtime_mutex_);
      retirement_ready_.wait(lock, [&] {
        if (retirement_stopping_) return true;
        for (const auto &[id, runtime] : retired_runtimes_) {
          (void)runtime;
          if (scheduled_retirements_.find(id) == scheduled_retirements_.end()) {
            return true;
          }
        }
        return false;
      });
      if (retirement_stopping_) return;
      for (const auto &[id, runtime] : retired_runtimes_) {
        (void)runtime;
        if (scheduled_retirements_.find(id) == scheduled_retirements_.end()) {
          candidate = id;
          break;
        }
      }
    }
    if (candidate != 0 && try_schedule_retired_runtime(candidate)) continue;
    std::unique_lock lock(retired_runtime_mutex_);
    retirement_ready_.wait_for(
        lock, std::chrono::milliseconds(10),
        [&] { return retirement_stopping_; });
    if (retirement_stopping_) return;
  }
}

std::size_t ProcessServices::retired_runtime_count() const noexcept {
  std::lock_guard lock(retired_runtime_mutex_);
  return retired_runtimes_.size();
}

bool ProcessServices::restart_required() const noexcept {
  return restart_required_.load(std::memory_order_acquire);
}

std::size_t ProcessServices::thread_count() const noexcept {
  std::lock_guard lock(retired_runtime_mutex_);
  return workers_.thread_count() + cleanup_->thread_count() +
      (retirement_retry_worker_.joinable() ? 1 : 0);
}

void ProcessServices::shutdown() noexcept {
  {
    std::lock_guard lock(retired_runtime_mutex_);
    retirement_stopping_ = true;
  }
  retirement_ready_.notify_all();
  if (retirement_retry_worker_.joinable()) retirement_retry_worker_.join();
  workers_.shutdown();
  {
    std::lock_guard lock(jvm_async_mutex_);
    jvm_async_completions_.clear();
  }
  cleanup_->drain_and_shutdown();
  std::unordered_map<SessionId, std::shared_ptr<RuntimeSession>> retired;
  {
    std::lock_guard lock(retired_runtime_mutex_);
    retired.swap(retired_runtimes_);
    scheduled_retirements_.clear();
  }
  for (auto &[id, runtime] : retired) {
    (void)id;
    runtime->cleanup_physical();
  }
  java_vm_.store(nullptr, std::memory_order_release);
}

ProcessServices &process_services() noexcept {
  static ProcessServices services;
  return services;
}

}  // namespace supernote::runtime
"""
    registration_bridge = """// Generated by supernote_module_generator. Do not edit.
#include <jni.h>

#include <android/log.h>
#include <dlfcn.h>
#include <stdint.h>

typedef jboolean (*SupernoteRuntimeRegistrar)(JNIEnv *, jobject, jstring);

JNIEXPORT jboolean JNICALL
Java_supernote_generated_runtime_SupernoteV4NativeRegistrationBridge_nativeRegister(
    JNIEnv *env,
    jobject bridge,
    jlong registrar_address,
    jstring generation_identity,
    jobject class_loader) {
  if (env == NULL || bridge == NULL || registrar_address == 0 ||
      generation_identity == NULL || class_loader == NULL) {
    return JNI_FALSE;
  }
  SupernoteRuntimeRegistrar registrar =
      (SupernoteRuntimeRegistrar)(uintptr_t)registrar_address;
  Dl_info registrar_info;
  if (dladdr((void *)registrar, &registrar_info) == 0 ||
      registrar_info.dli_fbase == NULL) {
    __android_log_print(
        ANDROID_LOG_ERROR, "SupernoteV4Registration",
        "published runtime registrar is no longer mapped");
    return JNI_FALSE;
  }
  const jboolean registered =
      registrar(env, class_loader, generation_identity);
  if (registered != JNI_TRUE) {
    __android_log_print(
        ANDROID_LOG_ERROR, "SupernoteV4Registration",
        "current runtime registrar rejected the plugin ClassLoader");
  }
  return registered;
}
"""
    bootstrap = f"""// Generated by supernote_module_generator. Do not edit.
#include <jni.h>
#include <jsi/jsi.h>

#include <android/log.h>
#include <ReactCommon/CallInvokerHolder.h>

#include <atomic>
#include <cstdint>
#include <functional>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>

#include "runtime_services.hpp"

namespace supernote::generated {{
void install_plugin_bindings(
    facebook::jsi::Runtime &runtime,
    const std::shared_ptr<supernote::runtime::RuntimeSession> &runtime_session);
}}

extern "C" __attribute__((visibility("hidden"))) jboolean
{component}_register_natives(
    JNIEnv *env, jobject class_loader, jstring generation_identity);

namespace {{

constexpr char kLogTag[] = "SupernoteV4Runtime";
constexpr char kLoadRequestProperty[] = {json.dumps(load_request_property)};
constexpr char kRegistrarProperty[] = {json.dumps(registrar_property)};
std::string g_generation_identity;
std::mutex g_mutex;
std::unordered_map<std::uint64_t,
                   std::shared_ptr<supernote::runtime::RuntimeSession>>
    g_sessions;

#if defined(SUPERNOTE_V4_WEAK_OBJECT_PROBE)
constexpr char kWeakProbeGlobal[] = "__supernoteV4Phase0WeakObjectProbe";
constexpr char kWeakProbeTargetGlobal[] =
    "__supernoteV4Phase0WeakObjectProbeTarget";

class WeakObjectProbeHost final : public facebook::jsi::HostObject {{
 public:
  WeakObjectProbeHost(
      facebook::jsi::Runtime &runtime,
      const facebook::jsi::Object &target) {{
    weak_.emplace(runtime, target);
    if (!lock_and_verify(runtime)) {{
      throw std::runtime_error("JSI WeakObject could not lock its live target");
    }}
    __android_log_print(
        ANDROID_LOG_INFO, kLogTag,
        "phase0 weak object created and locked on JS thread");
  }}

  ~WeakObjectProbeHost() override {{
    weak_.reset();
    __android_log_print(
        ANDROID_LOG_INFO, kLogTag,
        "phase0 weak object destroyed by runtime-managed HostObject teardown");
  }}

  facebook::jsi::Value get(
      facebook::jsi::Runtime &runtime,
      const facebook::jsi::PropNameID &name) override {{
    if (name.utf8(runtime) != "locked") {{
      return facebook::jsi::Value::undefined();
    }}
    const auto locked = lock_and_verify(runtime);
    __android_log_print(
        locked ? ANDROID_LOG_INFO : ANDROID_LOG_ERROR, kLogTag,
        "phase0 weak object JS-thread lock %s",
        locked ? "passed" : "failed");
    return facebook::jsi::Value(locked);
  }}

 private:
  bool lock_and_verify(facebook::jsi::Runtime &runtime) const {{
    if (!weak_) return false;
    auto value = weak_->lock(runtime);
    if (!value.isObject()) return false;
    auto token = value.asObject(runtime).getProperty(runtime, "token");
    return token.isNumber() && token.asNumber() == 42.0;
  }}

  std::optional<facebook::jsi::WeakObject> weak_;
}};

void install_weak_object_probe(facebook::jsi::Runtime &runtime) {{
  facebook::jsi::Object target(runtime);
  target.setProperty(runtime, "token", 42.0);
  auto probe = facebook::jsi::Object::createFromHostObject(
      runtime, std::make_shared<WeakObjectProbeHost>(runtime, target));
  runtime.global().setProperty(runtime, kWeakProbeGlobal, std::move(probe));
  runtime.global().setProperty(
      runtime, kWeakProbeTargetGlobal, std::move(target));
}}
#endif

class AttachedEnv {{
 public:
  explicit AttachedEnv(JavaVM *vm) : vm_(vm) {{
    if (vm_ == nullptr) return;
    const auto status = vm_->GetEnv(
        reinterpret_cast<void **>(&env_), JNI_VERSION_1_6);
    if (status == JNI_EDETACHED) {{
      if (vm_->AttachCurrentThread(&env_, nullptr) == JNI_OK) attached_ = true;
    }}
  }}
  ~AttachedEnv() {{
    if (attached_) vm_->DetachCurrentThread();
  }}
  JNIEnv *get() const noexcept {{ return env_; }}

 private:
  JavaVM *vm_{{nullptr}};
  JNIEnv *env_{{nullptr}};
  bool attached_{{false}};
}};

void clear_exception(JNIEnv *env, const char *operation) {{
  if (env == nullptr || !env->ExceptionCheck()) return;
  __android_log_print(
      ANDROID_LOG_ERROR, kLogTag, "%s raised a Java exception", operation);
  env->ExceptionDescribe();
  env->ExceptionClear();
}}

bool publish_runtime_registrar(JNIEnv *env) {{
  auto system_class = env->FindClass("java/lang/System");
  auto get_property = system_class == nullptr
      ? nullptr
      : env->GetStaticMethodID(
            system_class, "getProperty",
            "(Ljava/lang/String;)Ljava/lang/String;");
  auto set_property = system_class == nullptr
      ? nullptr
      : env->GetStaticMethodID(
            system_class, "setProperty",
            "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
  auto request_key = env->NewStringUTF(kLoadRequestProperty);
  auto request = get_property == nullptr || request_key == nullptr
      ? nullptr
      : static_cast<jstring>(env->CallStaticObjectMethod(
            system_class, get_property, request_key));
  if (env->ExceptionCheck() || request == nullptr) {{
    clear_exception(env, "read runtime generation request");
    return false;
  }}
  const char *request_chars = env->GetStringUTFChars(request, nullptr);
  if (request_chars == nullptr) {{
    clear_exception(env, "copy runtime generation request");
    return false;
  }}
  g_generation_identity.assign(request_chars);
  env->ReleaseStringUTFChars(request, request_chars);
  if (g_generation_identity.empty()) return false;

  const auto publication = g_generation_identity + ":" + std::to_string(
      reinterpret_cast<std::uintptr_t>(&{component}_register_natives));
  auto key = env->NewStringUTF(kRegistrarProperty);
  auto value = env->NewStringUTF(publication.c_str());
  if (set_property == nullptr || key == nullptr || value == nullptr) {{
    clear_exception(env, "prepare runtime registrar publication");
    return false;
  }}
  env->CallStaticObjectMethod(system_class, set_property, key, value);
  if (env->ExceptionCheck()) {{
    clear_exception(env, "publish runtime registrar");
    return false;
  }}
  return true;
}}

std::string utf8_bytes(JNIEnv *env, jbyteArray value) {{
  if (env == nullptr || value == nullptr) return {{}};
  const auto length = env->GetArrayLength(value);
  if (env->ExceptionCheck() || length < 0) {{
    clear_exception(env, "read coroutine failure");
    return "Kotlin coroutine implementation failed";
  }}
  std::string result(static_cast<std::size_t>(length), char{{}});
  if (length != 0) {{
    env->GetByteArrayRegion(
        value, 0, length, reinterpret_cast<jbyte *>(result.data()));
    if (env->ExceptionCheck()) {{
      clear_exception(env, "copy coroutine failure");
      return "Kotlin coroutine implementation failed";
    }}
  }}
  return result;
}}

void native_coroutine_complete(
    JNIEnv *env, jclass, jlong completion_id, jobject result,
    jbyteArray failure, jboolean cancelled) {{
  supernote::runtime::process_services().complete_jvm_async(
      static_cast<supernote::runtime::SessionId>(completion_id), env, result,
      cancelled == JNI_TRUE
          ? "CANCELLED"
          : (failure == nullptr ? "" : "IMPLEMENTATION_ERROR"),
      utf8_bytes(env, failure));
}}

void register_coroutine_bridge(JNIEnv *env, jobject class_loader) {{
  auto loader_class = env->GetObjectClass(class_loader);
  auto load_class = loader_class == nullptr
      ? nullptr
      : env->GetMethodID(
            loader_class, "loadClass", "(Ljava/lang/String;)Ljava/lang/Class;");
  auto name = env->NewStringUTF(
      "supernote.generated.runtime.SupernoteCoroutineBridge");
  auto bridge = load_class == nullptr || name == nullptr
      ? nullptr
      : env->CallObjectMethod(class_loader, load_class, name);
  if (env->ExceptionCheck() || bridge == nullptr) {{
    clear_exception(env, "load coroutine bridge");
    throw std::runtime_error("generated coroutine bridge is unavailable");
  }}
  JNINativeMethod methods[] = {{
      {{const_cast<char *>("nativeComplete"),
        const_cast<char *>("(JLjava/lang/Object;[BZ)V"),
        reinterpret_cast<void *>(&native_coroutine_complete)}},
  }};
  if (env->RegisterNatives(
          static_cast<jclass>(bridge), methods,
          static_cast<jint>(sizeof(methods) / sizeof(methods[0]))) != JNI_OK) {{
    clear_exception(env, "register coroutine bridge");
    throw std::runtime_error("cannot register coroutine bridge natives");
  }}
}}

std::shared_ptr<void> global_ref(JNIEnv *env, jobject value) {{
  if (env == nullptr || value == nullptr) return {{}};
  auto *global = env->NewGlobalRef(value);
  if (global == nullptr) throw std::runtime_error("cannot retain JVM object");
  JavaVM *vm = nullptr;
  if (env->GetJavaVM(&vm) != JNI_OK || vm == nullptr) {{
    env->DeleteGlobalRef(global);
    throw std::runtime_error("cannot resolve JavaVM");
  }}
  auto cleanup = supernote::runtime::process_services().cleanup();
  return std::shared_ptr<void>(global, [vm, cleanup](void *raw) {{
    auto release = [vm, raw] {{
      AttachedEnv attached(vm);
      if (auto *release_env = attached.get()) {{
        release_env->DeleteGlobalRef(static_cast<jobject>(raw));
      }}
    }};
    if (!cleanup || !cleanup->submit(release)) release();
  }});
}}

}}  // namespace

extern "C" JNIEXPORT jlong JNICALL
Java_supernote_generated_runtime_SupernoteV4Module_nativeInstall(
    JNIEnv *env, jobject module, jlong runtime_pointer, jobject class_loader,
    jobject platform_context, jobject call_invoker_holder) {{
  if (env == nullptr || module == nullptr || class_loader == nullptr ||
      platform_context == nullptr || call_invoker_holder == nullptr ||
      runtime_pointer == 0) {{
    return 0;
  }}
  try {{
    JavaVM *vm = nullptr;
    if (env->GetJavaVM(&vm) != JNI_OK || vm == nullptr) return 0;
    supernote::runtime::process_services().set_java_vm(vm);
    supernote::runtime::process_services().configure_worker_threads([vm] {{
      JNIEnv *worker_env = nullptr;
      bool attached = false;
      const auto status = vm->GetEnv(
          reinterpret_cast<void **>(&worker_env), JNI_VERSION_1_6);
      if (status == JNI_EDETACHED) {{
        if (vm->AttachCurrentThread(&worker_env, nullptr) != JNI_OK) {{
          throw std::runtime_error("cannot attach Supernote worker to JavaVM");
        }}
        attached = true;
      }} else if (status != JNI_OK) {{
        throw std::runtime_error("cannot inspect Supernote worker JVM state");
      }}
      return [vm, attached] {{
        if (attached) vm->DetachCurrentThread();
      }};
    }});
    register_coroutine_bridge(env, class_loader);
    auto loader_ref = global_ref(env, class_loader);
    auto context_ref = global_ref(env, platform_context);
    auto holder = facebook::jni::wrap_alias(
        reinterpret_cast<facebook::react::CallInvokerHolder::javaobject>(
            call_invoker_holder));
    auto call_invoker = holder->cthis()->getCallInvoker();
    if (!call_invoker) {{
      throw std::runtime_error("React Native JS CallInvoker is unavailable");
    }}
    auto scheduler = [call_invoker](
                         supernote::runtime::RuntimeSession::JsTask task) {{
      call_invoker->invokeAsync(
          [task = std::move(task)](
              facebook::jsi::Runtime &runtime) mutable {{
            task(static_cast<void *>(&runtime));
          }});
    }};
    auto session = supernote::runtime::RuntimeSession::create(
        std::move(scheduler), std::move(loader_ref), std::move(context_ref));
    auto *runtime = reinterpret_cast<facebook::jsi::Runtime *>(
        static_cast<std::uintptr_t>(runtime_pointer));
    supernote::generated::install_plugin_bindings(*runtime, session);
#if defined(SUPERNOTE_V4_WEAK_OBJECT_PROBE)
    install_weak_object_probe(*runtime);
#endif
    const auto session_id = session->id();
    {{
      std::lock_guard lock(g_mutex);
      g_sessions.emplace(session_id, std::move(session));
    }}
    __android_log_print(
        ANDROID_LOG_INFO, kLogTag, "installed runtime session %llu",
        static_cast<unsigned long long>(session_id));
    return static_cast<jlong>(session_id);
  }} catch (const std::exception &error) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag, "runtime installation failed: %s",
        error.what());
    return 0;
  }} catch (...) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag, "runtime installation failed");
    return 0;
  }}
}}

extern "C" JNIEXPORT void JNICALL
Java_supernote_generated_runtime_SupernoteV4Module_nativeInvalidate(
    JNIEnv *, jobject, jlong session_id) {{
  std::shared_ptr<supernote::runtime::RuntimeSession> session;
  {{
    std::lock_guard lock(g_mutex);
    auto found = g_sessions.find(static_cast<std::uint64_t>(session_id));
    if (found == g_sessions.end()) return;
    session = found->second;
  }}
  __android_log_print(
      ANDROID_LOG_INFO, kLogTag, "invalidating runtime session %llu",
      static_cast<unsigned long long>(session_id));
  const bool retained = session->invalidate();
  if (retained) {{
    std::lock_guard lock(g_mutex);
    auto found = g_sessions.find(static_cast<std::uint64_t>(session_id));
    if (found != g_sessions.end() && found->second == session) {{
      g_sessions.erase(found);
    }}
  }} else {{
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag,
        "SNV4_RESTART_REQUIRED: runtime retirement could not be guaranteed "
        "(retained=%zu limit=32); restart PluginHost",
        supernote::runtime::process_services().retired_runtime_count());
  }}
  __android_log_print(
      ANDROID_LOG_INFO, kLogTag,
      "logical invalidation completed; physical cleanup remains process-owned");
}}

extern "C" __attribute__((visibility("hidden"))) jboolean
{component}_register_natives(
    JNIEnv *env, jobject class_loader, jstring generation_identity) {{
  if (env == nullptr || class_loader == nullptr ||
      generation_identity == nullptr) return JNI_FALSE;
  const char *identity_chars =
      env->GetStringUTFChars(generation_identity, nullptr);
  if (identity_chars == nullptr) {{
    clear_exception(env, "read requested runtime generation identity");
    return JNI_FALSE;
  }}
  const bool generation_matches = g_generation_identity == identity_chars;
  env->ReleaseStringUTFChars(generation_identity, identity_chars);
  if (!generation_matches) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag,
        "generated runtime generation identity mismatch");
    return JNI_FALSE;
  }}
  auto loader_class = env->GetObjectClass(class_loader);
  auto load_class = loader_class == nullptr
      ? nullptr
      : env->GetMethodID(
            loader_class, "loadClass",
            "(Ljava/lang/String;)Ljava/lang/Class;");
  auto module_name = env->NewStringUTF(
      "supernote.generated.runtime.SupernoteV4Module");
  auto module_class = load_class == nullptr || module_name == nullptr
      ? nullptr
      : env->CallObjectMethod(class_loader, load_class, module_name);
  if (env->ExceptionCheck() || module_class == nullptr) {{
    clear_exception(env, "load generated runtime module");
    return JNI_FALSE;
  }}
  JNINativeMethod methods[] = {{
      {{const_cast<char *>("nativeInstall"),
        const_cast<char *>(
            "(JLjava/lang/ClassLoader;"
            "Lcom/facebook/react/bridge/ReactApplicationContext;"
            "Lcom/facebook/react/turbomodule/core/interfaces/"
            "CallInvokerHolder;)J"),
        reinterpret_cast<void *>(
            &Java_supernote_generated_runtime_SupernoteV4Module_nativeInstall)}},
      {{const_cast<char *>("nativeInvalidate"),
        const_cast<char *>("(J)V"),
        reinterpret_cast<void *>(
            &Java_supernote_generated_runtime_SupernoteV4Module_nativeInvalidate)}},
  }};
  if (env->RegisterNatives(
          static_cast<jclass>(module_class), methods,
          static_cast<jint>(sizeof(methods) / sizeof(methods[0]))) != JNI_OK) {{
    clear_exception(env, "register generated runtime natives");
    return JNI_FALSE;
  }}
  __android_log_print(
      ANDROID_LOG_INFO, kLogTag,
      "registered runtime natives for plugin ClassLoader %p", class_loader);
  return JNI_TRUE;
}}

extern "C" JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *java_vm, void *) {{
  JNIEnv *env = nullptr;
  if (java_vm == nullptr ||
      java_vm->GetEnv(
          reinterpret_cast<void **>(&env), JNI_VERSION_1_6) != JNI_OK ||
      env == nullptr) {{
    return JNI_ERR;
  }}
  supernote::runtime::process_services().set_java_vm(java_vm);
  return publish_runtime_registrar(env) ? JNI_VERSION_1_6 : JNI_ERR;
}}
"""
    ownership = {
        "schema_version": GENERATED_OWNERSHIP_SCHEMA_VERSION,
        "kind": GENERATED_OWNERSHIP_KIND,
        "component_name": component,
        "generator_version": registry.generator_version,
        "generated_files": [
            "CMakeLists.txt",
            "build.gradle",
            "consumer-rules.pro",
            "annotations/build.gradle",
            "annotations/src/main/java/supernote/generated/annotations/SupernotePluginAsync.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernoteConstructor.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernotePluginExport.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernotePluginInternal.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernotePluginObject.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernotePluginValue.java",
            "feature-registry.json",
            "ownership.json",
            "src/main/java/supernote/generated/runtime/SupernoteV4Module.kt",
            "src/main/java/supernote/generated/runtime/SupernoteCoroutineBridge.kt",
            "src/main/java/supernote/generated/runtime/SupernoteConversionBudget.kt",
            "src/feature_registry.cpp",
            "src/feature_registry.hpp",
            "src/runtime_services.cpp",
            "src/runtime_services.hpp",
            "include/supernote/runtime.hpp",
            "include/supernote/conversion.hpp",
            "include/supernote/cpp_objects.hpp",
            "src/runtime_bootstrap.cpp",
            "src/runtime_registration_bridge.c",
            "processor/build.gradle",
            "processor/src/main/kotlin/supernote/generated/processor/SupernoteV4Processor.kt",
            "processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider",
        ],
    }
    generated = {
        "CMakeLists.txt": cmake,
        "build.gradle": gradle,
        "consumer-rules.pro": consumer_keep_rules,
        "annotations/build.gradle": annotations_gradle,
        "annotations/src/main/java/supernote/generated/annotations/SupernotePluginAsync.java": render("v4.SupernotePluginAsync.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernoteConstructor.java": render("v4.SupernoteConstructor.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernotePluginExport.java": render("v4.SupernotePluginExport.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernotePluginInternal.java": render("v4.SupernotePluginInternal.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernotePluginObject.java": render("v4.SupernotePluginObject.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernotePluginValue.java": render("v4.SupernotePluginValue.java.tmpl", {}),
        "feature-registry.json": (
            json.dumps(registry.manifest(), indent=2, sort_keys=True) + "\n"
        ),
        "ownership.json": json.dumps(ownership, indent=2, sort_keys=True) + "\n",
        "src/main/java/supernote/generated/runtime/SupernoteV4Module.kt": render(
            "v4.SupernoteV4Module.kt.tmpl",
            {
                "NATIVE_LIBRARY_NAME": component,
                "NATIVE_REGISTRATION_LIBRARY_NAME": registration_component,
                "NATIVE_SOURCE_PROPERTY": source_property,
                "NATIVE_GENERATION_COUNT_PROPERTY": generation_count_property,
                "NATIVE_GENERATION_IDS_PROPERTY": generation_ids_property,
                "NATIVE_BINARY_REGISTRY_PREFIX": binary_registry_prefix,
                "NATIVE_LOAD_REQUEST_PROPERTY": load_request_property,
                "NATIVE_REGISTRAR_PROPERTY": registrar_property,
            },
        ),
        "src/main/java/supernote/generated/runtime/SupernoteCoroutineBridge.kt": render(
            "v4.SupernoteCoroutineBridge.kt.tmpl", {}
        ),
        "src/main/java/supernote/generated/runtime/SupernoteConversionBudget.kt": render_jvm_conversion_kernel(),
        "src/feature_registry.cpp": registry_source,
        "src/feature_registry.hpp": header,
        "src/runtime_services.cpp": services,
        "src/runtime_services.hpp": services_header,
        "include/supernote/runtime.hpp": public_runtime_header,
        "include/supernote/conversion.hpp": render_cpp_conversion_kernel(),
        "include/supernote/cpp_objects.hpp": render_cpp_object_runtime(),
        "src/runtime_bootstrap.cpp": bootstrap,
        "src/runtime_registration_bridge.c": registration_bridge,
        "processor/build.gradle": processor_gradle,
        "processor/src/main/kotlin/supernote/generated/processor/SupernoteV4Processor.kt": render(
            "v4.SupernoteV4Processor.kt.tmpl",
            {"GENERATOR_VERSION": registry.generator_version},
        ),
        "processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider": render(
            "v4.processor.provider.tmpl", {}
        ),
    }
    for entry in registry.features:
        suffix = entry.feature.feature_id.removeprefix("supernote:feature:")
        relative = f"inputs/{suffix}/cpp-semantic.json"
        generated[relative] = (
            json.dumps(
                entry.source_semantic_api.manifest(), indent=2, sort_keys=True
            )
            + "\n"
        )
        ownership["generated_files"].append(relative)
    generated["ownership.json"] = (
        json.dumps(ownership, indent=2, sort_keys=True) + "\n"
    )
    return generated


def stage_plugin_runtime(plugin_root: Path, registry: PluginRuntimeRegistry) -> Path:
    """Stage a complete replacement without mutating the active component."""

    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    parent = destination.parent
    parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.tmp-", dir=parent)
    )
    try:
        for relative, content in generated_runtime_files(registry).items():
            target = temporary / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
        return temporary
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def activate_plugin_runtime(staged: Path, plugin_root: Path) -> Path | None:
    """Atomically activate staged generated files and return a rollback backup."""

    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    backup = None
    if destination.exists():
        backup = destination.parent / (
            f".{destination.name}.backup-{uuid.uuid4().hex}"
        )
        os.replace(destination, backup)
    try:
        os.replace(staged, destination)
        return backup
    except Exception:
        if backup is not None and backup.exists():
            os.replace(backup, destination)
        raise


def finalize_plugin_runtime(backup: Path | None) -> None:
    if backup is not None:
        shutil.rmtree(backup, ignore_errors=True)


def restore_plugin_runtime(plugin_root: Path, backup: Path | None) -> None:
    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    if backup is None:
        shutil.rmtree(destination, ignore_errors=True)
        return
    failed = destination.parent / f".{destination.name}.failed-{uuid.uuid4().hex}"
    if destination.exists():
        os.replace(destination, failed)
    os.replace(backup, destination)
    shutil.rmtree(failed, ignore_errors=True)


def generate_plugin_runtime(
    plugin_root: Path,
    registry: PluginRuntimeRegistry,
) -> Path:
    staged = stage_plugin_runtime(plugin_root, registry)
    backup = activate_plugin_runtime(staged, plugin_root)
    finalize_plugin_runtime(backup)
    return plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
