"""Generate the one plugin-level V2 runtime/build component."""
from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import tempfile
import uuid

from .feature_model import PluginRuntimeRegistry
from .templates import render


RUNTIME_RELATIVE_ROOT = Path("android/.supernote-module/v2-runtime")


def generated_runtime_files(registry: PluginRuntimeRegistry) -> dict[str, str]:
    """Return deterministic generated files for one compiled plugin component."""

    feature_rows = "\n".join(
        "    {"
        + json.dumps(entry.feature.feature_id)
        + ", "
        + json.dumps(entry.feature.public_name)
        + "},"
        for entry in registry.features
    )
    if not feature_rows:
        feature_rows = "    // No generated features are currently registered."
    component = registry.component_name
    jvm_roots = [
        f"local_modules/{entry.feature.npm_name}/{entry.feature.roots.jvm}"
        for entry in registry.features
    ]
    native_roots = [
        f"local_modules/{entry.feature.npm_name}/{entry.feature.roots.native}"
        for entry in registry.features
    ]
    jvm_root_rows = "\n".join(
        f"    new File(supernotePluginRoot, {json.dumps(path)}),"
        for path in jvm_roots
    )
    native_root_rows = "\n".join(
        f"    new File(supernotePluginRoot, {json.dumps(path)}),"
        for path in native_roots
    )
    cmake_native_roots = "\n".join(
        f'    "${{CMAKE_CURRENT_LIST_DIR}}/../../../{path}"'
        for path in native_roots
    )
    encoded_roots = "\n".join(
        f"{entry.feature.feature_id}\tlocal_modules/"
        f"{entry.feature.npm_name}/{entry.feature.roots.jvm}"
        for entry in registry.features
    )
    cmake = f"""# Generated by supernote_module_generator. Do not edit.
cmake_minimum_required(VERSION 3.22.1)
project({component} LANGUAGES C CXX)

if(NOT DEFINED SUPERNOTE_VARIANT)
  message(FATAL_ERROR "SUPERNOTE_VARIANT must be debug or release")
endif()

set(SUPERNOTE_NATIVE_ROOTS
{cmake_native_roots}
)
set(SUPERNOTE_USER_SOURCES)
foreach(SUPERNOTE_NATIVE_ROOT IN LISTS SUPERNOTE_NATIVE_ROOTS)
  file(GLOB_RECURSE SUPERNOTE_FEATURE_SOURCES CONFIGURE_DEPENDS
      "${{SUPERNOTE_NATIVE_ROOT}}/*.c"
      "${{SUPERNOTE_NATIVE_ROOT}}/*.cc"
      "${{SUPERNOTE_NATIVE_ROOT}}/*.cpp"
      "${{SUPERNOTE_NATIVE_ROOT}}/*.cxx")
  list(APPEND SUPERNOTE_USER_SOURCES ${{SUPERNOTE_FEATURE_SOURCES}})
endforeach()
file(GLOB SUPERNOTE_GENERATED_BINDINGS CONFIGURE_DEPENDS
    "${{CMAKE_CURRENT_LIST_DIR}}/build/generated/supernote/${{SUPERNOTE_VARIANT}}/jni/*.cpp")
if(NOT SUPERNOTE_GENERATED_BINDINGS)
  message(FATAL_ERROR "Supernote generated JSI bindings are missing")
endif()

add_library({component} SHARED
    src/feature_registry.cpp
    src/runtime_bootstrap.cpp
    src/runtime_services.cpp
    ${{SUPERNOTE_USER_SOURCES}}
    ${{SUPERNOTE_GENERATED_BINDINGS}}
)

find_package(Threads REQUIRED)
find_package(ReactAndroid REQUIRED CONFIG)
target_compile_features({component} PRIVATE cxx_std_23)
set_target_properties({component} PROPERTIES C_STANDARD 23 C_STANDARD_REQUIRED YES)
target_include_directories(
    {component} PRIVATE ${{SUPERNOTE_NATIVE_ROOTS}} "${{CMAKE_CURRENT_LIST_DIR}}/src")
target_link_libraries({component} PRIVATE Threads::Threads ReactAndroid::jsi log)
"""
    gradle = f"""// Generated by supernote_module_generator. Do not edit.
plugins {{
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp' version '2.0.21-1.0.28'
}}

def supernotePluginRoot = rootProject.projectDir.parentFile
def supernoteJvmRoots = [
{jvm_root_rows}
]
def supernoteNativeRoots = [
{native_root_rows}
]

android {{
    namespace 'supernote.generated.{component}'
    compileSdk rootProject.ext.compileSdkVersion
    ndkVersion rootProject.ext.ndkVersion

    defaultConfig {{
        minSdk rootProject.ext.minSdkVersion
        ndk {{
            abiFilters 'arm64-v8a'
        }}
        externalNativeBuild {{
            cmake {{
                arguments '-DANDROID_STL=c++_shared'
            }}
        }}
    }}

    externalNativeBuild {{
        cmake {{
            path file('CMakeLists.txt')
            version '3.22.1'
        }}
    }}
    buildFeatures {{
        prefab true
    }}
    buildTypes {{
        debug {{
            externalNativeBuild {{
                cmake {{ arguments '-DSUPERNOTE_VARIANT=debug' }}
            }}
        }}
        release {{
            externalNativeBuild {{
                cmake {{ arguments '-DSUPERNOTE_VARIANT=release' }}
            }}
        }}
    }}
    sourceSets {{
        main.java.srcDirs(supernoteJvmRoots)
    }}
}}

dependencies {{
    implementation('com.facebook.react:react-android')
    compileOnly project(':supernote-v2-annotations')
    ksp project(':supernote-v2-processor')
}}

ksp {{
    arg('supernotePluginRoot', supernotePluginRoot.absolutePath)
    arg('supernoteFeatureRoots', {json.dumps(encoded_roots)})
}}

kotlin {{
    jvmToolchain(17)
}}

def supernotePython = System.getenv('SUPERNOTE_PYTHON') ?: 'python3'
def supernoteCommonScript = file('common_codegen.py')
def supernoteTypescriptOutputs = {json.dumps([
        f"${{supernotePluginRoot}}/local_modules/{entry.feature.npm_name}/index.d.ts"
        for entry in registry.features
    ])}.collect {{ file(it.replace('${{supernotePluginRoot}}', supernotePluginRoot.absolutePath)) }}

['Debug', 'Release'].each {{ buildVariant ->
    def variantName = buildVariant.toLowerCase()
    def commonTask = tasks.register("generateSupernote${{buildVariant}}Semantics", Exec) {{
        inputs.file(file('feature-registry.json'))
        inputs.dir(file('inputs'))
        supernoteNativeRoots.each {{ nativeRoot -> inputs.dir(nativeRoot) }}
        inputs.files(fileTree(layout.buildDirectory.dir(
            "generated/ksp/${{variantName}}/resources"
        )))
        outputs.dir(layout.buildDirectory.dir("generated/supernote/${{variantName}}"))
        outputs.files(supernoteTypescriptOutputs)
        commandLine(
            supernotePython,
            supernoteCommonScript.absolutePath,
            '--plugin-root',
            supernotePluginRoot.absolutePath,
            '--runtime-root',
            projectDir.absolutePath,
            '--variant',
            variantName,
        )
    }}
    afterEvaluate {{
        commonTask.configure {{
            dependsOn tasks.named("ksp${{buildVariant}}Kotlin")
        }}
    }}
    tasks.matching {{ task ->
        task.name == "externalNativeBuild${{buildVariant}}" ||
            task.name == "configureCMake${{buildVariant}}[arm64-v8a]"
    }}.configureEach {{ dependsOn commonTask }}
}}
"""
    annotations_gradle = """// Generated by supernote_module_generator. Do not edit.
plugins {
    id 'java-library'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
"""
    processor_gradle = """// Generated by supernote_module_generator. Do not edit.
plugins {
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation project(':supernote-v2-annotations')
    implementation 'com.google.devtools.ksp:symbol-processing-api:2.0.21-1.0.28'
}

kotlin {
    jvmToolchain(17)
}
"""
    header = """// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>

namespace supernote::generated {

struct FeatureDescriptor {
  const char *feature_id;
  const char *public_name;
};

const FeatureDescriptor *feature_registry_data() noexcept;
std::size_t feature_registry_size() noexcept;

}  // namespace supernote::generated
"""
    registry_source = f"""// Generated by supernote_module_generator. Do not edit.
#include "feature_registry.hpp"

#include <array>

namespace supernote::generated {{
namespace {{

constexpr std::array<FeatureDescriptor, {len(registry.features)}> kFeatures{{{{
{feature_rows}
}}}};

}}  // namespace

const FeatureDescriptor *feature_registry_data() noexcept {{
  return kFeatures.data();
}}

std::size_t feature_registry_size() noexcept {{
  return kFeatures.size();
}}

}}  // namespace supernote::generated
"""
    services_header = r"""// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <atomic>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <stdexcept>
#include <type_traits>
#include <unordered_map>
#include <utility>

namespace supernote::runtime {

using SessionId = std::uint64_t;

class CancellationToken {
 public:
  CancellationToken() = default;
  bool is_cancelled() const noexcept;

 private:
  explicit CancellationToken(std::shared_ptr<std::atomic<bool>> state);
  std::shared_ptr<std::atomic<bool>> state_;
  friend class CancellationSource;
};

class CancellationSource {
 public:
  CancellationSource();
  CancellationToken token() const noexcept;
  bool request_cancel() const noexcept;

 private:
  std::shared_ptr<std::atomic<bool>> state_;
};

class BoundedExecutor {
 public:
  using Task = std::function<void(CancellationToken)>;

  class WorkHandle {
   public:
    WorkHandle() = default;
    bool accepted() const noexcept;
    bool cancel() const noexcept;
    CancellationToken token() const noexcept;

   private:
    struct Control;
    explicit WorkHandle(std::shared_ptr<Control> control);
    std::shared_ptr<Control> control_;
    friend class BoundedExecutor;
  };

  BoundedExecutor(std::size_t worker_count, std::size_t queue_capacity);
  ~BoundedExecutor();
  BoundedExecutor(const BoundedExecutor &) = delete;
  BoundedExecutor &operator=(const BoundedExecutor &) = delete;

  WorkHandle submit(Task task);
  void shutdown() noexcept;

 private:
  struct State;
  std::shared_ptr<State> state_;
};

class DeferredDestruction {
 public:
  DeferredDestruction();
  ~DeferredDestruction();
  DeferredDestruction(const DeferredDestruction &) = delete;
  DeferredDestruction &operator=(const DeferredDestruction &) = delete;

  bool submit(std::function<void()> cleanup) noexcept;
  void drain_and_shutdown() noexcept;

 private:
  struct State;
  std::shared_ptr<State> state_;
};

template <typename T>
class ManagedRef {
 public:
  ManagedRef() = default;
  ManagedRef(std::shared_ptr<T> value,
             std::shared_ptr<DeferredDestruction> cleanup)
      : value_(std::move(value)), cleanup_(std::move(cleanup)) {}
  ManagedRef(const ManagedRef &) = default;
  ManagedRef &operator=(const ManagedRef &other) {
    if (this == &other) return *this;
    reset();
    value_ = other.value_;
    cleanup_ = other.cleanup_;
    return *this;
  }
  ManagedRef(ManagedRef &&) noexcept = default;
  ManagedRef &operator=(ManagedRef && other) noexcept {
    if (this == &other) return *this;
    reset();
    value_ = std::move(other.value_);
    cleanup_ = std::move(other.cleanup_);
    return *this;
  }
  ~ManagedRef() { reset(); }

  T *get() const noexcept { return value_.get(); }
  T &operator*() const noexcept { return *value_; }
  T *operator->() const noexcept { return value_.get(); }
  explicit operator bool() const noexcept { return static_cast<bool>(value_); }

  void reset() noexcept {
    auto value = std::move(value_);
    auto cleanup = cleanup_;
    cleanup_.reset();
    if (!value) return;
    if (!cleanup || !cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) {
      // Component shutdown is the only rejected-admission case. At that
      // boundary all generated work has already been drained, so inline
      // release is safe and cannot run on a live JavaScript callback.
      value.reset();
    }
  }

 private:
  std::shared_ptr<T> value_;
  std::shared_ptr<DeferredDestruction> cleanup_;
};

class FeatureSession;

class RuntimeSession : public std::enable_shared_from_this<RuntimeSession> {
 public:
  using JsTask = std::function<void(void *runtime)>;
  using JsScheduler = std::function<void(JsTask)>;

  static std::shared_ptr<RuntimeSession> create(
      JsScheduler scheduler,
      std::shared_ptr<void> plugin_class_loader = {},
      std::shared_ptr<void> platform_context = {});

  SessionId id() const noexcept;
  bool active() const noexcept;
  bool schedule(JsTask task) noexcept;
  void invalidate() noexcept;
  std::shared_ptr<void> plugin_class_loader() const noexcept;
  std::shared_ptr<void> platform_context() const noexcept;

 private:
  RuntimeSession(SessionId id, JsScheduler scheduler,
                 std::shared_ptr<void> plugin_class_loader,
                 std::shared_ptr<void> platform_context);
  void add_feature(const std::shared_ptr<FeatureSession> &feature);

  SessionId id_;
  JsScheduler scheduler_;
  std::shared_ptr<void> plugin_class_loader_;
  std::shared_ptr<void> platform_context_;
  std::atomic<bool> active_{true};
  mutable std::mutex mutex_;
  std::unordered_map<SessionId, std::shared_ptr<FeatureSession>> features_;
  friend class FeatureSession;
};

enum class FeatureState { ACTIVE, CLOSING, INACTIVE };
enum class OperationWinner {
  PENDING,
  COMPLETING,
  CANCELLED_BY_FEATURE,
  CANCELLED_BY_RUNTIME,
};

class PendingOperation {
 public:
  using TeardownRejection = std::function<void(void *runtime)>;

  SessionId id() const noexcept;
  OperationWinner winner() const noexcept;
  CancellationToken cancellation_token() const noexcept;
  void set_work(BoundedExecutor::WorkHandle work) noexcept;

 private:
  PendingOperation(SessionId id, TeardownRejection rejection);
  bool claim(OperationWinner winner) noexcept;
  TeardownRejection take_rejection() noexcept;

  SessionId id_;
  std::atomic<OperationWinner> winner_{OperationWinner::PENDING};
  CancellationSource cancellation_;
  std::mutex mutex_;
  BoundedExecutor::WorkHandle work_;
  TeardownRejection rejection_;
  friend class FeatureSession;
};

class FeatureSession : public std::enable_shared_from_this<FeatureSession> {
 public:
  static std::shared_ptr<FeatureSession> create(
      const std::shared_ptr<RuntimeSession> &runtime,
      std::shared_ptr<DeferredDestruction> cleanup);

  SessionId id() const noexcept;
  FeatureState state() const noexcept;
  std::shared_ptr<RuntimeSession> runtime() const noexcept;
  std::shared_ptr<PendingOperation> accept(
      PendingOperation::TeardownRejection rejection);
  std::shared_ptr<PendingOperation> accept_factory(
      std::function<PendingOperation::TeardownRejection(SessionId)> factory);
  bool schedule_completion(
      const std::shared_ptr<PendingOperation> &operation,
      RuntimeSession::JsTask completion) noexcept;
  void close_feature() noexcept;
  void close_runtime() noexcept;

  template <typename T, typename Factory>
  ManagedRef<T> service(const std::string &declaration_id,
                        Factory &&factory) {
    static_assert(std::is_invocable_r_v<std::shared_ptr<T>, Factory>);
    std::shared_ptr<ServiceSlot> slot;
    std::uint64_t attempt = 0;
    {
      std::unique_lock lock(mutex_);
      if (state_.load(std::memory_order_acquire) != FeatureState::ACTIVE) {
        throw std::runtime_error("feature session is closed");
      }
      auto &stored = services_[declaration_id];
      if (!stored) stored = std::make_shared<ServiceSlot>();
      slot = stored;
    }
    {
      std::unique_lock lock(slot->mutex);
      if (slot->value) {
        return ManagedRef<T>(std::static_pointer_cast<T>(slot->value), cleanup_);
      }
      if (slot->initializing) {
        attempt = slot->attempt;
        slot->ready.wait(lock, [&] { return !slot->initializing; });
        if (slot->value) {
          return ManagedRef<T>(std::static_pointer_cast<T>(slot->value), cleanup_);
        }
        if (slot->completed_attempt == attempt && slot->failure) {
          std::rethrow_exception(slot->failure);
        }
      }
      slot->initializing = true;
      attempt = ++slot->attempt;
      slot->failure = nullptr;
    }
    try {
      auto created = std::invoke(std::forward<Factory>(factory));
      if (!created) throw std::runtime_error("service factory returned null");
      {
        std::unique_lock feature_lock(mutex_);
        std::unique_lock slot_lock(slot->mutex);
        if (state_.load(std::memory_order_acquire) != FeatureState::ACTIVE) {
          slot->initializing = false;
          slot->completed_attempt = attempt;
          slot->failure = std::make_exception_ptr(
              std::runtime_error("feature closed during service construction"));
          slot->ready.notify_all();
          defer_release(std::move(created));
          std::rethrow_exception(slot->failure);
        }
        slot->value = created;
        slot->initializing = false;
        slot->completed_attempt = attempt;
        slot->ready.notify_all();
      }
      return ManagedRef<T>(std::move(created), cleanup_);
    } catch (...) {
      std::unique_lock lock(slot->mutex);
      if (slot->initializing && slot->attempt == attempt) {
        slot->initializing = false;
        slot->completed_attempt = attempt;
        slot->failure = std::current_exception();
        slot->ready.notify_all();
      }
      throw;
    }
  }

 private:
  struct ServiceSlot {
    std::mutex mutex;
    std::condition_variable ready;
    bool initializing = false;
    std::uint64_t attempt = 0;
    std::uint64_t completed_attempt = 0;
    std::shared_ptr<void> value;
    std::exception_ptr failure;
  };

  FeatureSession(SessionId id, std::shared_ptr<RuntimeSession> runtime,
                 std::shared_ptr<DeferredDestruction> cleanup);
  void close(bool runtime_teardown) noexcept;
  void erase_pending(SessionId operation_id) noexcept;

  template <typename T>
  void defer_release(std::shared_ptr<T> value) noexcept {
    if (!value) return;
    auto cleanup = cleanup_;
    if (!cleanup || !cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) {
      value.reset();
    }
  }

  SessionId id_;
  std::weak_ptr<RuntimeSession> runtime_;
  std::shared_ptr<DeferredDestruction> cleanup_;
  std::atomic<FeatureState> state_{FeatureState::ACTIVE};
  mutable std::mutex mutex_;
  std::unordered_map<SessionId, std::shared_ptr<PendingOperation>> pending_;
  std::unordered_map<std::string, std::shared_ptr<ServiceSlot>> services_;
};

class ProcessServices {
 public:
  ProcessServices();
  ~ProcessServices();
  ProcessServices(const ProcessServices &) = delete;
  ProcessServices &operator=(const ProcessServices &) = delete;

  BoundedExecutor &workers() noexcept;
  std::shared_ptr<DeferredDestruction> cleanup() const noexcept;
  void set_java_vm(void *java_vm) noexcept;
  void *java_vm() const noexcept;

 private:
  BoundedExecutor workers_;
  std::shared_ptr<DeferredDestruction> cleanup_;
  std::atomic<void *> java_vm_{nullptr};
};

ProcessServices &process_services() noexcept;

}  // namespace supernote::runtime
"""
    services = r"""// Generated by supernote_module_generator. Do not edit.
#include "runtime_services.hpp"

#include <algorithm>
#include <deque>
#include <stdexcept>
#include <thread>
#include <utility>
#include <vector>

namespace supernote::runtime {
namespace {

std::atomic<SessionId> next_session_id{1};

SessionId allocate_session_id() noexcept {
  return next_session_id.fetch_add(1, std::memory_order_relaxed);
}

}  // namespace

CancellationToken::CancellationToken(
    std::shared_ptr<std::atomic<bool>> state) : state_(std::move(state)) {}

bool CancellationToken::is_cancelled() const noexcept {
  return state_ && state_->load(std::memory_order_acquire);
}

CancellationSource::CancellationSource()
    : state_(std::make_shared<std::atomic<bool>>(false)) {}

CancellationToken CancellationSource::token() const noexcept {
  return CancellationToken(state_);
}

bool CancellationSource::request_cancel() const noexcept {
  return state_ && !state_->exchange(true, std::memory_order_acq_rel);
}

struct BoundedExecutor::WorkHandle::Control {
  std::uint64_t id = 0;
  CancellationSource cancellation;
  std::function<bool(std::uint64_t)> cancel_queued;
  bool accepted = false;
};

struct BoundedExecutor::State {
  struct Item {
    std::uint64_t id;
    CancellationSource cancellation;
    Task task;
  };

  explicit State(std::size_t capacity) : capacity(capacity) {}
  std::mutex mutex;
  std::condition_variable ready;
  std::deque<Item> queue;
  std::vector<std::thread> workers;
  std::size_t capacity;
  std::uint64_t next_id = 1;
  bool stopped = false;
};

BoundedExecutor::WorkHandle::WorkHandle(std::shared_ptr<Control> control)
    : control_(std::move(control)) {}

bool BoundedExecutor::WorkHandle::accepted() const noexcept {
  return control_ && control_->accepted;
}

bool BoundedExecutor::WorkHandle::cancel() const noexcept {
  if (!control_) return false;
  control_->cancellation.request_cancel();
  return control_->cancel_queued && control_->cancel_queued(control_->id);
}

CancellationToken BoundedExecutor::WorkHandle::token() const noexcept {
  return control_ ? control_->cancellation.token() : CancellationToken{};
}

BoundedExecutor::BoundedExecutor(std::size_t worker_count,
                                 std::size_t queue_capacity)
    : state_(std::make_shared<State>(queue_capacity)) {
  if (worker_count == 0 || queue_capacity == 0) {
    throw std::invalid_argument("executor size and capacity must be positive");
  }
  for (std::size_t index = 0; index < worker_count; ++index) {
    state_->workers.emplace_back([state = state_] {
      while (true) {
        State::Item item;
        {
          std::unique_lock lock(state->mutex);
          state->ready.wait(lock, [&] {
            return state->stopped || !state->queue.empty();
          });
          if (state->queue.empty()) {
            if (state->stopped) return;
            continue;
          }
          item = std::move(state->queue.front());
          state->queue.pop_front();
        }
        if (item.cancellation.token().is_cancelled()) continue;
        try {
          item.task(item.cancellation.token());
        } catch (...) {
          // Generated completion paths translate failures. An escaping task
          // must never terminate the shared executor.
        }
      }
    });
  }
}

BoundedExecutor::~BoundedExecutor() { shutdown(); }

BoundedExecutor::WorkHandle BoundedExecutor::submit(Task task) {
  if (!task) return {};
  auto control = std::make_shared<WorkHandle::Control>();
  auto state = state_;
  {
    std::lock_guard lock(state->mutex);
    if (state->stopped || state->queue.size() >= state->capacity) {
      return WorkHandle(control);
    }
    control->id = state->next_id++;
    control->accepted = true;
    state->queue.push_back(
        {control->id, control->cancellation, std::move(task)});
  }
  control->cancel_queued = [weak = std::weak_ptr<State>(state)](
                               std::uint64_t id) {
    auto locked = weak.lock();
    if (!locked) return false;
    std::lock_guard guard(locked->mutex);
    auto found = std::find_if(
        locked->queue.begin(), locked->queue.end(),
        [id](const State::Item &item) { return item.id == id; });
    if (found == locked->queue.end()) return false;
    locked->queue.erase(found);
    return true;
  };
  state->ready.notify_one();
  return WorkHandle(std::move(control));
}

void BoundedExecutor::shutdown() noexcept {
  auto state = state_;
  if (!state) return;
  {
    std::lock_guard lock(state->mutex);
    if (state->stopped) return;
    state->stopped = true;
    for (auto &item : state->queue) item.cancellation.request_cancel();
    state->queue.clear();
  }
  state->ready.notify_all();
  for (auto &worker : state->workers) {
    if (worker.joinable()) worker.join();
  }
  state->workers.clear();
}

struct DeferredDestruction::State {
  std::mutex mutex;
  std::condition_variable ready;
  std::deque<std::function<void()>> queue;
  std::thread worker;
  bool stopping = false;
};

DeferredDestruction::DeferredDestruction() : state_(std::make_shared<State>()) {
  state_->worker = std::thread([state = state_] {
    while (true) {
      std::function<void()> cleanup;
      {
        std::unique_lock lock(state->mutex);
        state->ready.wait(lock, [&] {
          return state->stopping || !state->queue.empty();
        });
        if (state->queue.empty() && state->stopping) return;
        cleanup = std::move(state->queue.front());
        state->queue.pop_front();
      }
      try {
        cleanup();
      } catch (...) {
        // Destructors/cleanup never cross into JSI and never stop the facility.
      }
    }
  });
}

DeferredDestruction::~DeferredDestruction() { drain_and_shutdown(); }

bool DeferredDestruction::submit(std::function<void()> cleanup) noexcept {
  if (!cleanup) return true;
  auto state = state_;
  try {
    {
      std::lock_guard lock(state->mutex);
      if (state->stopping) return false;
      state->queue.push_back(std::move(cleanup));
    }
    state->ready.notify_one();
    return true;
  } catch (...) {
    return false;
  }
}

void DeferredDestruction::drain_and_shutdown() noexcept {
  auto state = state_;
  if (!state) return;
  {
    std::lock_guard lock(state->mutex);
    state->stopping = true;
  }
  state->ready.notify_all();
  if (state->worker.joinable()) state->worker.join();
}

RuntimeSession::RuntimeSession(SessionId id, JsScheduler scheduler,
                               std::shared_ptr<void> plugin_class_loader,
                               std::shared_ptr<void> platform_context)
    : id_(id),
      scheduler_(std::move(scheduler)),
      plugin_class_loader_(std::move(plugin_class_loader)),
      platform_context_(std::move(platform_context)) {}

std::shared_ptr<RuntimeSession> RuntimeSession::create(
    JsScheduler scheduler, std::shared_ptr<void> plugin_class_loader,
    std::shared_ptr<void> platform_context) {
  if (!scheduler) throw std::invalid_argument("JS scheduler is required");
  return std::shared_ptr<RuntimeSession>(new RuntimeSession(
      allocate_session_id(), std::move(scheduler),
      std::move(plugin_class_loader), std::move(platform_context)));
}

SessionId RuntimeSession::id() const noexcept { return id_; }

bool RuntimeSession::active() const noexcept {
  return active_.load(std::memory_order_acquire);
}

bool RuntimeSession::schedule(JsTask task) noexcept {
  if (!task || !active()) return false;
  auto weak = weak_from_this();
  const auto expected = id_;
  JsScheduler scheduler;
  {
    std::lock_guard lock(mutex_);
    if (!active() || !scheduler_) return false;
    scheduler = scheduler_;
  }
  try {
    scheduler([weak, expected, task = std::move(task)](void *runtime) mutable {
      auto session = weak.lock();
      if (!session || session->id_ != expected || !session->active() ||
          runtime == nullptr) {
        return;
      }
      task(runtime);
    });
    return true;
  } catch (...) {
    return false;
  }
}

void RuntimeSession::add_feature(
    const std::shared_ptr<FeatureSession> &feature) {
  std::lock_guard lock(mutex_);
  if (!active()) throw std::runtime_error("runtime session is inactive");
  features_[feature->id()] = feature;
}

void RuntimeSession::invalidate() noexcept {
  if (!active_.exchange(false, std::memory_order_acq_rel)) return;
  std::vector<std::shared_ptr<FeatureSession>> features;
  {
    std::lock_guard lock(mutex_);
    for (auto &[id, feature] : features_) {
      (void)id;
      features.push_back(std::move(feature));
    }
    features_.clear();
    plugin_class_loader_.reset();
    platform_context_.reset();
    scheduler_ = {};
  }
  for (auto &feature : features) feature->close_runtime();
}

std::shared_ptr<void> RuntimeSession::plugin_class_loader() const noexcept {
  std::lock_guard lock(mutex_);
  return plugin_class_loader_;
}

std::shared_ptr<void> RuntimeSession::platform_context() const noexcept {
  std::lock_guard lock(mutex_);
  return platform_context_;
}

PendingOperation::PendingOperation(SessionId id, TeardownRejection rejection)
    : id_(id), rejection_(std::move(rejection)) {}

SessionId PendingOperation::id() const noexcept { return id_; }

OperationWinner PendingOperation::winner() const noexcept {
  return winner_.load(std::memory_order_acquire);
}

CancellationToken PendingOperation::cancellation_token() const noexcept {
  return cancellation_.token();
}

void PendingOperation::set_work(BoundedExecutor::WorkHandle work) noexcept {
  std::lock_guard lock(mutex_);
  work_ = std::move(work);
  if (winner() != OperationWinner::PENDING) work_.cancel();
}

bool PendingOperation::claim(OperationWinner winner) noexcept {
  auto expected = OperationWinner::PENDING;
  if (!winner_.compare_exchange_strong(expected, winner,
                                       std::memory_order_acq_rel)) {
    return false;
  }
  if (winner == OperationWinner::CANCELLED_BY_FEATURE ||
      winner == OperationWinner::CANCELLED_BY_RUNTIME) {
    cancellation_.request_cancel();
    std::lock_guard lock(mutex_);
    work_.cancel();
  }
  return true;
}

PendingOperation::TeardownRejection PendingOperation::take_rejection() noexcept {
  std::lock_guard lock(mutex_);
  return std::move(rejection_);
}

FeatureSession::FeatureSession(SessionId id,
                               std::shared_ptr<RuntimeSession> runtime,
                               std::shared_ptr<DeferredDestruction> cleanup)
    : id_(id), runtime_(std::move(runtime)), cleanup_(std::move(cleanup)) {}

std::shared_ptr<FeatureSession> FeatureSession::create(
    const std::shared_ptr<RuntimeSession> &runtime,
    std::shared_ptr<DeferredDestruction> cleanup) {
  if (!runtime || !runtime->active()) {
    throw std::invalid_argument("active runtime session is required");
  }
  if (!cleanup) throw std::invalid_argument("cleanup facility is required");
  auto feature = std::shared_ptr<FeatureSession>(new FeatureSession(
      allocate_session_id(), runtime, std::move(cleanup)));
  runtime->add_feature(feature);
  return feature;
}

SessionId FeatureSession::id() const noexcept { return id_; }

FeatureState FeatureSession::state() const noexcept {
  return state_.load(std::memory_order_acquire);
}

std::shared_ptr<RuntimeSession> FeatureSession::runtime() const noexcept {
  return runtime_.lock();
}

std::shared_ptr<PendingOperation> FeatureSession::accept(
    PendingOperation::TeardownRejection rejection) {
  std::lock_guard lock(mutex_);
  auto runtime = runtime_.lock();
  if (state() != FeatureState::ACTIVE || !runtime || !runtime->active()) {
    return {};
  }
  auto operation = std::shared_ptr<PendingOperation>(
      new PendingOperation(allocate_session_id(), std::move(rejection)));
  pending_.emplace(operation->id(), operation);
  return operation;
}

std::shared_ptr<PendingOperation> FeatureSession::accept_factory(
    std::function<PendingOperation::TeardownRejection(SessionId)> factory) {
  std::lock_guard lock(mutex_);
  auto runtime = runtime_.lock();
  if (!factory || state() != FeatureState::ACTIVE || !runtime ||
      !runtime->active()) {
    return {};
  }
  const auto id = allocate_session_id();
  auto operation = std::shared_ptr<PendingOperation>(
      new PendingOperation(id, factory(id)));
  pending_.emplace(operation->id(), operation);
  return operation;
}

bool FeatureSession::schedule_completion(
    const std::shared_ptr<PendingOperation> &operation,
    RuntimeSession::JsTask completion) noexcept {
  if (!operation || !completion || state() != FeatureState::ACTIVE) return false;
  auto runtime = runtime_.lock();
  if (!runtime || !runtime->active()) return false;
  auto weak = weak_from_this();
  const auto expected_feature = id_;
  return runtime->schedule(
      [weak, expected_feature, operation,
       completion = std::move(completion)](void *js_runtime) mutable {
        auto feature = weak.lock();
        if (!feature || feature->id_ != expected_feature) return;
        {
          std::lock_guard lock(feature->mutex_);
          if (feature->state() != FeatureState::ACTIVE ||
              !operation->claim(OperationWinner::COMPLETING)) {
            return;
          }
          feature->pending_.erase(operation->id());
        }
        operation->take_rejection();
        completion(js_runtime);
      });
}

void FeatureSession::close_feature() noexcept { close(false); }

void FeatureSession::close_runtime() noexcept { close(true); }

void FeatureSession::close(bool runtime_teardown) noexcept {
  std::vector<std::shared_ptr<PendingOperation>> pending;
  std::vector<std::shared_ptr<void>> services;
  {
    std::lock_guard lock(mutex_);
    if (state() != FeatureState::ACTIVE) return;
    state_.store(FeatureState::CLOSING, std::memory_order_release);
    for (auto &[id, operation] : pending_) {
      (void)id;
      pending.push_back(std::move(operation));
    }
    pending_.clear();
    for (auto &[id, slot] : services_) {
      (void)id;
      std::lock_guard slot_lock(slot->mutex);
      if (slot->value) services.push_back(std::move(slot->value));
    }
    services_.clear();
  }

  auto runtime = runtime_.lock();
  for (auto &operation : pending) {
    const auto outcome = runtime_teardown
        ? OperationWinner::CANCELLED_BY_RUNTIME
        : OperationWinner::CANCELLED_BY_FEATURE;
    if (!operation->claim(outcome)) continue;
    auto rejection = operation->take_rejection();
    if (!runtime_teardown && runtime && runtime->active() && rejection) {
      runtime->schedule(std::move(rejection));
    }
  }
  for (auto &service : services) defer_release(std::move(service));
  runtime_.reset();
  state_.store(FeatureState::INACTIVE, std::memory_order_release);
}

void FeatureSession::erase_pending(SessionId operation_id) noexcept {
  std::lock_guard lock(mutex_);
  pending_.erase(operation_id);
}

ProcessServices::ProcessServices()
    : workers_(std::max<std::size_t>(1, std::thread::hardware_concurrency()),
               256),
      cleanup_(std::make_shared<DeferredDestruction>()) {}

ProcessServices::~ProcessServices() {
  workers_.shutdown();
  cleanup_->drain_and_shutdown();
}

BoundedExecutor &ProcessServices::workers() noexcept { return workers_; }

std::shared_ptr<DeferredDestruction> ProcessServices::cleanup() const noexcept {
  return cleanup_;
}

void ProcessServices::set_java_vm(void *java_vm) noexcept {
  java_vm_.store(java_vm, std::memory_order_release);
}

void *ProcessServices::java_vm() const noexcept {
  return java_vm_.load(std::memory_order_acquire);
}

ProcessServices &process_services() noexcept {
  static ProcessServices services;
  return services;
}

}  // namespace supernote::runtime
"""
    bootstrap = f"""// Generated by supernote_module_generator. Do not edit.
#include <jni.h>
#include <jsi/jsi.h>

#include <android/log.h>

#include <atomic>
#include <cstdint>
#include <functional>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <unordered_map>
#include <utility>

#include "runtime_services.hpp"

namespace supernote::generated {{
void install_plugin_bindings(
    facebook::jsi::Runtime &runtime,
    const std::shared_ptr<supernote::runtime::RuntimeSession> &runtime_session);
}}

namespace {{

constexpr char kLogTag[] = "SupernoteV2Runtime";
std::mutex g_mutex;
std::unordered_map<std::uint64_t,
                   std::shared_ptr<supernote::runtime::RuntimeSession>>
    g_sessions;
struct ScheduledTask {{
  std::uint64_t session_id;
  supernote::runtime::RuntimeSession::JsTask task;
}};
struct SchedulerBridge {{
  std::atomic<std::uint64_t> session_id{{0}};
}};
std::unordered_map<std::uint64_t, ScheduledTask> g_js_tasks;
std::atomic<std::uint64_t> g_next_task{{1}};

class AttachedEnv {{
 public:
  explicit AttachedEnv(JavaVM *vm) : vm_(vm) {{
    if (vm_ == nullptr) return;
    const auto status = vm_->GetEnv(
        reinterpret_cast<void **>(&env_), JNI_VERSION_1_6);
    if (status == JNI_EDETACHED) {{
      if (vm_->AttachCurrentThread(&env_, nullptr) == JNI_OK) attached_ = true;
    }}
  }}
  ~AttachedEnv() {{
    if (attached_) vm_->DetachCurrentThread();
  }}
  JNIEnv *get() const noexcept {{ return env_; }}

 private:
  JavaVM *vm_{{nullptr}};
  JNIEnv *env_{{nullptr}};
  bool attached_{{false}};
}};

void clear_exception(JNIEnv *env, const char *operation) {{
  if (env == nullptr || !env->ExceptionCheck()) return;
  __android_log_print(
      ANDROID_LOG_ERROR, kLogTag, "%s raised a Java exception", operation);
  env->ExceptionDescribe();
  env->ExceptionClear();
}}

std::shared_ptr<void> global_ref(JNIEnv *env, jobject value) {{
  if (env == nullptr || value == nullptr) return {{}};
  auto *global = env->NewGlobalRef(value);
  if (global == nullptr) throw std::runtime_error("cannot retain JVM object");
  JavaVM *vm = nullptr;
  if (env->GetJavaVM(&vm) != JNI_OK || vm == nullptr) {{
    env->DeleteGlobalRef(global);
    throw std::runtime_error("cannot resolve JavaVM");
  }}
  auto cleanup = supernote::runtime::process_services().cleanup();
  return std::shared_ptr<void>(global, [vm, cleanup](void *raw) {{
    auto release = [vm, raw] {{
      AttachedEnv attached(vm);
      if (auto *release_env = attached.get()) {{
        release_env->DeleteGlobalRef(static_cast<jobject>(raw));
      }}
    }};
    if (!cleanup || !cleanup->submit(release)) release();
  }});
}}

void schedule_through_module(
    JavaVM *vm,
    const std::shared_ptr<void> &module,
    jmethodID schedule_method,
    std::uint64_t session_id,
    supernote::runtime::RuntimeSession::JsTask task) {{
  const auto task_id = g_next_task.fetch_add(1, std::memory_order_relaxed);
  {{
    std::lock_guard lock(g_mutex);
    g_js_tasks.emplace(
        task_id, ScheduledTask{{session_id, std::move(task)}});
  }}
  AttachedEnv attached(vm);
  auto *env = attached.get();
  if (env == nullptr) {{
    std::lock_guard lock(g_mutex);
    g_js_tasks.erase(task_id);
    throw std::runtime_error("cannot attach scheduler thread to JVM");
  }}
  env->CallVoidMethod(
      static_cast<jobject>(module.get()), schedule_method,
      static_cast<jlong>(task_id));
  if (env->ExceptionCheck()) {{
    clear_exception(env, "scheduleOnJsThread");
    std::lock_guard lock(g_mutex);
    g_js_tasks.erase(task_id);
    throw std::runtime_error("cannot schedule completion on JS thread");
  }}
}}

}}  // namespace

extern "C" JNIEXPORT jlong JNICALL
Java_supernote_generated_runtime_SupernoteV2Module_nativeInstall(
    JNIEnv *env, jobject module, jlong runtime_pointer, jobject class_loader,
    jobject platform_context) {{
  if (env == nullptr || module == nullptr || class_loader == nullptr ||
      platform_context == nullptr || runtime_pointer == 0) {{
    return 0;
  }}
  try {{
    JavaVM *vm = nullptr;
    if (env->GetJavaVM(&vm) != JNI_OK || vm == nullptr) return 0;
    supernote::runtime::process_services().set_java_vm(vm);
    auto module_ref = global_ref(env, module);
    auto loader_ref = global_ref(env, class_loader);
    auto context_ref = global_ref(env, platform_context);
    auto module_class = env->GetObjectClass(module);
    auto schedule_method = module_class == nullptr
        ? nullptr
        : env->GetMethodID(module_class, "scheduleOnJsThread", "(J)V");
    if (schedule_method == nullptr) {{
      clear_exception(env, "resolve scheduleOnJsThread");
      throw std::runtime_error("generated JS scheduler method is missing");
    }}
    auto bridge = std::make_shared<SchedulerBridge>();
    auto scheduler = [vm, module_ref, schedule_method, bridge](
                         supernote::runtime::RuntimeSession::JsTask task) {{
      schedule_through_module(
          vm, module_ref, schedule_method,
          bridge->session_id.load(std::memory_order_acquire),
          std::move(task));
    }};
    auto session = supernote::runtime::RuntimeSession::create(
        std::move(scheduler), std::move(loader_ref), std::move(context_ref));
    auto *runtime = reinterpret_cast<facebook::jsi::Runtime *>(
        static_cast<std::uintptr_t>(runtime_pointer));
    supernote::generated::install_plugin_bindings(*runtime, session);
    const auto session_id = session->id();
    bridge->session_id.store(session_id, std::memory_order_release);
    {{
      std::lock_guard lock(g_mutex);
      g_sessions.emplace(session_id, std::move(session));
    }}
    return static_cast<jlong>(session_id);
  }} catch (const std::exception &error) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag, "runtime installation failed: %s",
        error.what());
    return 0;
  }} catch (...) {{
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag, "runtime installation failed");
    return 0;
  }}
}}

extern "C" JNIEXPORT void JNICALL
Java_supernote_generated_runtime_SupernoteV2Module_nativeInvalidate(
    JNIEnv *, jobject, jlong session_id) {{
  std::shared_ptr<supernote::runtime::RuntimeSession> session;
  {{
    std::lock_guard lock(g_mutex);
    auto found = g_sessions.find(static_cast<std::uint64_t>(session_id));
    if (found == g_sessions.end()) return;
    session = std::move(found->second);
    g_sessions.erase(found);
    for (auto task = g_js_tasks.begin(); task != g_js_tasks.end();) {{
      if (task->second.session_id == static_cast<std::uint64_t>(session_id)) {{
        task = g_js_tasks.erase(task);
      }} else {{
        ++task;
      }}
    }}
  }}
  session->invalidate();
}}

extern "C" JNIEXPORT void JNICALL
Java_supernote_generated_runtime_SupernoteV2Module_nativeRunJsTask(
    JNIEnv *, jobject, jlong task_id, jlong runtime_pointer) {{
  supernote::runtime::RuntimeSession::JsTask task;
  {{
    std::lock_guard lock(g_mutex);
    auto found = g_js_tasks.find(static_cast<std::uint64_t>(task_id));
    if (found == g_js_tasks.end()) return;
    task = std::move(found->second.task);
    g_js_tasks.erase(found);
  }}
  task(reinterpret_cast<void *>(static_cast<std::uintptr_t>(runtime_pointer)));
}}

extern "C" JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *java_vm, void *) {{
  supernote::runtime::process_services().set_java_vm(java_vm);
  return JNI_VERSION_1_6;
}}
"""
    ownership = {
        "schema_version": 1,
        "kind": "supernote_plugin_runtime_ownership",
        "component_name": component,
        "generator_version": registry.generator_version,
        "generated_files": [
            "CMakeLists.txt",
            "build.gradle",
            "common_codegen.py",
            "common_support/__init__.py",
            "common_support/binding_codegen.py",
            "common_support/cpp_projection.py",
            "common_support/jvm_manifest.py",
            "common_support/jvm_codegen.py",
            "common_support/jvm_projection.py",
            "common_support/lowering.py",
            "common_support/semantic.py",
            "common_support/source_models.py",
            "common_support/typescript_codegen.py",
            "annotations/build.gradle",
            "annotations/src/main/java/supernote/generated/annotations/SupernoteAsync.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernoteConstructor.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernoteExport.java",
            "annotations/src/main/java/supernote/generated/annotations/SupernoteInternal.java",
            "feature-registry.json",
            "ownership.json",
            "src/main/java/supernote/generated/runtime/SupernoteV2Module.kt",
            "src/feature_registry.cpp",
            "src/feature_registry.hpp",
            "src/runtime_services.cpp",
            "src/runtime_services.hpp",
            "src/runtime_bootstrap.cpp",
            "processor/build.gradle",
            "processor/src/main/kotlin/supernote/generated/processor/SupernoteV2Processor.kt",
            "processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider",
        ],
    }
    generated = {
        "CMakeLists.txt": cmake,
        "build.gradle": gradle,
        "common_codegen.py": render(
            "v2.common_codegen.py.tmpl",
            {"GENERATOR_VERSION": registry.generator_version},
        ),
        "common_support/__init__.py": "",
        "common_support/binding_codegen.py": _support_source("binding_codegen.py"),
        "common_support/cpp_projection.py": _support_source("cpp_projection.py"),
        "common_support/jvm_manifest.py": _support_source("jvm_manifest.py"),
        "common_support/jvm_codegen.py": _support_source("jvm_codegen.py"),
        "common_support/jvm_projection.py": _support_source("jvm_projection.py"),
        "common_support/lowering.py": _support_source("lowering.py"),
        "common_support/semantic.py": _support_source("semantic.py"),
        "common_support/source_models.py": _support_source("source_models.py"),
        "common_support/typescript_codegen.py": _support_source("typescript_codegen.py"),
        "annotations/build.gradle": annotations_gradle,
        "annotations/src/main/java/supernote/generated/annotations/SupernoteAsync.java": render("v2.SupernoteAsync.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernoteConstructor.java": render("v2.SupernoteConstructor.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernoteExport.java": render("v2.SupernoteExport.java.tmpl", {}),
        "annotations/src/main/java/supernote/generated/annotations/SupernoteInternal.java": render("v2.SupernoteInternal.java.tmpl", {}),
        "feature-registry.json": (
            json.dumps(registry.manifest(), indent=2, sort_keys=True) + "\n"
        ),
        "ownership.json": json.dumps(ownership, indent=2, sort_keys=True) + "\n",
        "src/main/java/supernote/generated/runtime/SupernoteV2Module.kt": render(
            "v2.SupernoteV2Module.kt.tmpl",
            {"NATIVE_LIBRARY_NAME": component},
        ),
        "src/feature_registry.cpp": registry_source,
        "src/feature_registry.hpp": header,
        "src/runtime_services.cpp": services,
        "src/runtime_services.hpp": services_header,
        "src/runtime_bootstrap.cpp": bootstrap,
        "processor/build.gradle": processor_gradle,
        "processor/src/main/kotlin/supernote/generated/processor/SupernoteV2Processor.kt": render(
            "v2.SupernoteV2Processor.kt.tmpl",
            {"GENERATOR_VERSION": registry.generator_version},
        ),
        "processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider": render(
            "v2.processor.provider.tmpl", {}
        ),
    }
    for entry in registry.features:
        suffix = entry.feature.feature_id.removeprefix("supernote:feature:")
        relative = f"inputs/{suffix}/cpp-semantic.json"
        generated[relative] = (
            json.dumps(
                entry.source_semantic_api.manifest(), indent=2, sort_keys=True
            )
            + "\n"
        )
        ownership["generated_files"].append(relative)
    generated["ownership.json"] = (
        json.dumps(ownership, indent=2, sort_keys=True) + "\n"
    )
    return generated


def _support_source(name: str) -> str:
    return (Path(__file__).resolve().parent / name).read_text(encoding="utf-8")


def stage_plugin_runtime(plugin_root: Path, registry: PluginRuntimeRegistry) -> Path:
    """Stage a complete replacement without mutating the active component."""

    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    parent = destination.parent
    parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.tmp-", dir=parent)
    )
    try:
        for relative, content in generated_runtime_files(registry).items():
            target = temporary / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
        return temporary
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def activate_plugin_runtime(staged: Path, plugin_root: Path) -> Path | None:
    """Atomically activate staged generated files and return a rollback backup."""

    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    backup = None
    if destination.exists():
        backup = destination.parent / (
            f".{destination.name}.backup-{uuid.uuid4().hex}"
        )
        os.replace(destination, backup)
    try:
        os.replace(staged, destination)
        return backup
    except Exception:
        if backup is not None and backup.exists():
            os.replace(backup, destination)
        raise


def finalize_plugin_runtime(backup: Path | None) -> None:
    if backup is not None:
        shutil.rmtree(backup, ignore_errors=True)


def restore_plugin_runtime(plugin_root: Path, backup: Path | None) -> None:
    destination = plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
    if backup is None:
        shutil.rmtree(destination, ignore_errors=True)
        return
    failed = destination.parent / f".{destination.name}.failed-{uuid.uuid4().hex}"
    if destination.exists():
        os.replace(destination, failed)
    os.replace(backup, destination)
    shutil.rmtree(failed, ignore_errors=True)


def generate_plugin_runtime(
    plugin_root: Path,
    registry: PluginRuntimeRegistry,
) -> Path:
    staged = stage_plugin_runtime(plugin_root, registry)
    backup = activate_plugin_runtime(staged, plugin_root)
    finalize_plugin_runtime(backup)
    return plugin_root.resolve() / RUNTIME_RELATIVE_ROOT
