"""Generate the public TypeScript contract from common Supernote semantics."""
from __future__ import annotations

from .reachability import PublicApi, compute_public_api
from .semantic import (
    ExecutionMode,
    MemberScope,
    SemanticApi,
    SemanticBinding,
    SemanticEnumDeclaration,
    SemanticObjectDeclaration,
    SemanticValueDeclaration,
)
from .semantic_types import ScalarKind, SemanticType, SemanticTypeKind


_SCALARS = {
    ScalarKind.BOOL: "boolean",
    ScalarKind.INT32: "number",
    ScalarKind.INT64: "bigint",
    ScalarKind.FLOAT32: "number",
    ScalarKind.FLOAT64: "number",
    ScalarKind.STRING: "string",
    ScalarKind.BYTES: "Uint8Array",
}


def render_typescript(feature_name: str, api: SemanticApi) -> str:
    public = compute_public_api(api, feature_name=feature_name)
    declaration_names = {item.type_id: item.name for item in public.declarations}
    declarations = [
        _declaration(item, public, declaration_names)
        for item in public.declarations
    ]

    # Retain the old class records while their Phase 4 replacement tests are
    # still useful. Generated declarations never depend on this compatibility path.
    legacy_interfaces = []
    legacy_properties = []
    for item in api.classes:
        if not item.capabilities.javascript_public:
            continue
        methods = [
            _method(binding, declaration_names)
            for binding in item.methods
            if binding.capabilities.javascript_public
        ]
        parameters = _parameters(item.constructor.parameters, declaration_names)
        method_body = "\n".join(methods)
        legacy_interfaces.append(
            f"export interface {item.name} {{\n"
            f"{method_body}\n"
            "}\n\n"
            f"export interface {item.name}Factory {{\n"
            f"  create({parameters}): {item.name};\n"
            "}"
        )
        legacy_properties.append(f"  {item.name}: {item.name}Factory;")

    root_properties = list(legacy_properties)
    for item in sorted(public.declarations, key=lambda value: (value.name, value.type_id)):
        members = []
        if isinstance(item, SemanticObjectDeclaration):
            if item.constructor is not None:
                members.append(
                    "    create: "
                    + _callable(item.constructor.parameters, SemanticType.object_ref(item.type_id), declaration_names)
                    + ";"
                )
            members.extend(
                _method(method, declaration_names, indent="    ")
                for method in sorted(item.methods, key=lambda value: (value.name, value.binding_id))
                if method.capabilities.javascript_public
                and method.member_scope is MemberScope.STATIC
            )
        namespace_body = "\n".join(members)
        suffix = f" & {{\n{namespace_body}\n  }}" if members else ""
        root_properties.append(
            f"  {item.name}: SupernoteTypeCompanion<{item.name}>{suffix};"
        )
    root_properties.extend(
        _method(binding, declaration_names) for binding in public.functions
    )
    declaration_prefix = "\n\n".join(legacy_interfaces + declarations)
    if declaration_prefix:
        declaration_prefix += "\n\n"
    body = "\n".join(root_properties)
    return (
        "/* Generated by supernote_module_generator. Do not edit. */\n"
        "export type SupernoteErrorCode =\n"
        "  | 'RESOURCE_EXHAUSTED'\n"
        "  | 'CANCELLED'\n"
        "  | 'FEATURE_CLOSED'\n"
        "  | 'IMPLEMENTATION_ERROR'\n"
        "  | 'INTERNAL';\n\n"
        "export class SupernoteError extends Error {\n"
        "  constructor(code: SupernoteErrorCode, message: string);\n"
        "  readonly code: SupernoteErrorCode;\n"
        "}\n\n"
        "export type SupernoteValidationReason =\n"
        "  | 'ARITY_MISMATCH'\n"
        "  | 'TYPE_MISMATCH'\n"
        "  | 'NOMINAL_MISMATCH'\n"
        "  | 'MISSING_FIELD'\n"
        "  | 'INVALID_ENUM'\n"
        "  | 'OUT_OF_RANGE'\n"
        "  | 'LIMIT_EXCEEDED';\n\n"
        "export interface SupernoteValidationDetails {\n"
        "  readonly reason: SupernoteValidationReason;\n"
        "  readonly path: string;\n"
        "  readonly expected: string;\n"
        "  readonly actual: string;\n"
        "}\n\n"
        "export type SupernoteTypeError = TypeError & SupernoteValidationDetails;\n"
        "export type SupernoteRangeError = RangeError & SupernoteValidationDetails;\n"
        "export type SupernoteValidationResult =\n"
        "  | {readonly ok: true}\n"
        "  | {readonly ok: false; readonly error: SupernoteTypeError | SupernoteRangeError};\n\n"
        "export interface SupernoteCallable<Arguments extends unknown[], Result> {\n"
        "  (...args: Arguments): Result;\n"
        "  accepts(...args: unknown[]): boolean;\n"
        "  checkArguments(...args: unknown[]): SupernoteValidationResult;\n"
        "}\n\n"
        "export interface SupernoteTypeCompanion<Value> {\n"
        "  is(value: unknown): value is Value;\n"
        "  check(value: unknown): SupernoteValidationResult;\n"
        "}\n\n"
        "export type SupernoteFeatureStatus =\n"
        "  | 'available'\n"
        "  | 'runtime-unavailable'\n"
        "  | 'feature-unavailable';\n\n"
        "export interface SupernoteNativeObjectInfo {\n"
        "  readonly type: string;\n"
        "  readonly originFamily: 'cpp' | 'jvm';\n"
        "}\n\n"
        "export function isFeatureAvailable(): boolean;\n"
        "export function getFeatureStatus(): SupernoteFeatureStatus;\n"
        "export function nativeObjectInfo(value: unknown): SupernoteNativeObjectInfo | undefined;\n"
        "export function isSupernoteTypeError(value: unknown): value is SupernoteTypeError;\n"
        "export function isSupernoteRangeError(value: unknown): value is SupernoteRangeError;\n\n"
        f"{declaration_prefix}"
        f"export interface {feature_name}Feature {{\n{body}\n}}\n\n"
        f"declare const feature: {feature_name}Feature;\n"
        "export default feature;\n"
    )


def render_semantic_type(
    semantic_type: SemanticType,
    declaration_names: dict[str, str],
) -> str:
    """Render one public semantic type with the TypeScript generator's rules."""

    return _type(semantic_type, declaration_names)


def _declaration(item, public: PublicApi, names: dict[str, str]) -> str:
    if isinstance(item, SemanticEnumDeclaration):
        constants = " | ".join(repr(constant) for constant in item.constants)
        return f"export type {item.name} = {constants};"
    if isinstance(item, SemanticValueDeclaration):
        fields = "\n".join(
            f"  {field.name}: {_type(field.type, names)};" for field in item.fields
        )
        return f"export interface {item.name} {{\n{fields}\n}}"
    assert isinstance(item, SemanticObjectDeclaration)
    brand = f"__supernoteBrand_{item.name}"
    members = [f"  readonly [{brand}]: void;"]
    if item.type_id in public.object_instances:
        for field in item.fields:
            readonly = "readonly " if not field.mutable else ""
            members.append(
                f"  {readonly}{field.name}: {_type(field.type, names)};"
            )
        members.extend(
            _method(method, names)
            for method in sorted(item.methods, key=lambda value: (value.name, value.binding_id))
            if method.capabilities.javascript_public
            and method.member_scope is MemberScope.INSTANCE
        )
    member_body = "\n".join(members)
    return (
        f"declare const {brand}: unique symbol;\n"
        f"export interface {item.name} {{\n{member_body}\n}}"
    )


def _parameters(parameters, names: dict[str, str]) -> str:
    return ", ".join(
        f"{parameter.name}: {_type(parameter.type, names)}"
        for parameter in parameters
    )


def _method(
    binding: SemanticBinding,
    names: dict[str, str],
    *,
    indent: str = "  ",
) -> str:
    result = _type(binding.result, names)
    if binding.execution is ExecutionMode.ASYNC:
        result = f"Promise<{result}>"
    arguments = ", ".join(
        f"{parameter.name}: {_type(parameter.type, names)}"
        for parameter in binding.parameters
    )
    return (
        f"{indent}{binding.name}: "
        f"SupernoteCallable<[{arguments}], {result}>;"
    )


def _callable(parameters, result: SemanticType, names: dict[str, str]) -> str:
    arguments = ", ".join(
        f"{parameter.name}: {_type(parameter.type, names)}"
        for parameter in parameters
    )
    return f"SupernoteCallable<[{arguments}], {_type(result, names)}>"


def _type(semantic_type: SemanticType, names: dict[str, str]) -> str:
    if semantic_type.kind is SemanticTypeKind.VOID:
        return "void"
    if semantic_type.kind is SemanticTypeKind.SCALAR:
        assert semantic_type.scalar is not None
        return _SCALARS[semantic_type.scalar]
    if semantic_type.type_id is not None:
        return names[semantic_type.type_id]
    assert semantic_type.element is not None
    inner = _type(semantic_type.element, names)
    if semantic_type.kind is SemanticTypeKind.NULLABLE:
        return f"{inner} | null"
    if semantic_type.element.kind is SemanticTypeKind.NULLABLE:
        inner = f"({inner})"
    return f"{inner}[]"
