"""Generate the public TypeScript contract from common Supernote semantics."""
from __future__ import annotations

from .semantic import ExecutionMode, SemanticApi, SemanticBinding, SemanticType


_TYPES = {
    SemanticType.VOID: "void",
    SemanticType.BOOL: "boolean",
    SemanticType.INT32: "number",
    SemanticType.INT64: "bigint",
    SemanticType.FLOAT32: "number",
    SemanticType.FLOAT64: "number",
    SemanticType.STRING: "string",
    SemanticType.BYTES: "Uint8Array",
}


def render_typescript(feature_name: str, api: SemanticApi) -> str:
    object_interfaces = []
    object_properties = []
    for item in api.classes:
        if not item.capabilities.javascript_public:
            continue
        methods = [
            _method(binding)
            for binding in item.methods
            if binding.capabilities.javascript_public
        ]
        method_body = "\n".join(methods)
        parameters = ", ".join(
            f"{parameter.name}: {_TYPES[parameter.type]}"
            for parameter in item.constructor.parameters
        )
        object_interfaces.append(
            f"export interface {item.name} {{\n"
            f"{method_body}\n"
            "}\n\n"
            f"export interface {item.name}Factory {{\n"
            f"  create({parameters}): {item.name};\n"
            "}"
        )
        object_properties.append(f"  {item.name}: {item.name}Factory;")

    functions = [
        _method(binding)
        for binding in api.functions
        if binding.capabilities.javascript_public
    ]
    body = "\n".join(object_properties + functions)
    object_prefix = (
        "\n\n".join(object_interfaces) + "\n\n" if object_interfaces else ""
    )
    return (
        "/* Generated by supernote_module_generator. Do not edit. */\n"
        "export type SupernoteErrorCode =\n"
        "  | 'RESOURCE_EXHAUSTED'\n"
        "  | 'CANCELLED'\n"
        "  | 'FEATURE_CLOSED'\n"
        "  | 'IMPLEMENTATION_ERROR'\n"
        "  | 'INTERNAL';\n\n"
        "export class SupernoteError extends Error {\n"
        "  readonly code: SupernoteErrorCode;\n"
        "}\n\n"
        f"{object_prefix}"
        f"export interface {feature_name}Feature {{\n{body}\n}}\n\n"
        f"declare const feature: {feature_name}Feature;\n"
        "export default feature;\n"
    )


def _method(binding: SemanticBinding) -> str:
    parameters = ", ".join(
        f"{parameter.name}: {_TYPES[parameter.type]}"
        for parameter in binding.parameters
    )
    result = _TYPES[binding.result]
    if binding.execution is ExecutionMode.ASYNC:
        result = f"Promise<{result}>"
    return f"  {binding.name}({parameters}): {result};"
